# Nymph configuration
maxwidth = 200
statsoffset = 22
theme = catppuccin
iconpack = nerd
layout = full
modules = "os,host,kernel,cpu,desktop,terminal,shell,packages,uptime,memory,disk,battery,footer"
json = false
nocolor = false
customlogo = ""
footericons = ""
footerpadding = 7
