/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@mkitty_proto.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@mkitty_proto.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__dyW7vpmfeTYw8kX3EXuaJA[3];
typedef NimStringV2 tyArray__Seu7uK9aaOSN0BK3EAjjSHw[4];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg {
	NI a;
	NI b;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2743)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToLowerAsciiStr)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1832)(NimStringV2 s_p0, NimStringV2 sub_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstrformat_u492)(NimStringV2* dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, encode__pureZbase64_u42)(NIM_CHAR* s_p0, NI s_p0Len_0, NIM_BOOL safe_p1);
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1285)(NimStringV2 s_p0, tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg x_p1);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2492)(NimStringV2* s_p0);
static N_INLINE(tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u254)(FILE* f_p0, NimStringV2 s_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 sep_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5543)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_2 = { 4 | NIM_STRLIT_FLAG, "TERM" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_3 = {4, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_2};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_4 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_5 = {0, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_6 = { 12 | NIM_STRLIT_FLAG, "TERM_PROGRAM" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_7 = {12, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_6};
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_8 = {0, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_4};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_9 = { 17 | NIM_STRLIT_FLAG, "TERMINAL_EMULATOR" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_10 = {17, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_9};
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_11 = {0, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_4};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_12 = { 5 | NIM_STRLIT_FLAG, "kitty" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_13 = { 7 | NIM_STRLIT_FLAG, "wezterm" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_14 = { 7 | NIM_STRLIT_FLAG, "ghostty" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_15 = { 7 | NIM_STRLIT_FLAG, "konsole" };
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_16 = { 15 | NIM_STRLIT_FLAG, "KITTY_WINDOW_ID" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_17 = {15, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_16};
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_18 = {0, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_19 = { 15 | NIM_STRLIT_FLAG, "WEZTERM_VERSION" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_20 = {15, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_19};
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_21 = {0, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_4};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_22 = { 18 | NIM_STRLIT_FLAG, "WEZTERM_EXECUTABLE" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_23 = {18, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_22};
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_24 = {0, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_4};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_25 = { 21 | NIM_STRLIT_FLAG, "GHOSTTY_RESOURCES_DIR" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_26 = {21, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_25};
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_27 = {0, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_28 = { 15 | NIM_STRLIT_FLAG, "KONSOLE_VERSION" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_29 = {15, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_28};
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_30 = {0, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_31 = { 20 | NIM_STRLIT_FLAG, "KONSOLE_DBUS_SESSION" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_32 = {20, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_31};
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_33 = {0, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_4};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_34 = { 3 | NIM_STRLIT_FLAG, "a=T" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_35 = {3, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_34};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_36 = { 5 | NIM_STRLIT_FLAG, "f=100" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_37 = {5, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_36};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_38 = { 3 | NIM_STRLIT_FLAG, "t=d" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_39 = {3, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_38};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_40 = { 3 | NIM_STRLIT_FLAG, "q=2" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_41 = {3, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_40};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_42 = { 3 | NIM_STRLIT_FLAG, "C=1" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_43 = {3, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_42};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_44 = { 2 | NIM_STRLIT_FLAG, "c=" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_45 = {2, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_44};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_46 = { 2 | NIM_STRLIT_FLAG, "r=" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_47 = {2, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_46};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_48 = { 2 | NIM_STRLIT_FLAG, "m=" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_49 = {2, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_48};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_50 = { 1 | NIM_STRLIT_FLAG, "1" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_51 = {1, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_50};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_52 = { 1 | NIM_STRLIT_FLAG, "0" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_53 = {1, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_52};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_54 = { 3 | NIM_STRLIT_FLAG, "\033_G" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_55 = {3, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_54};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_56 = { 1 | NIM_STRLIT_FLAG, "," };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_57 = {1, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_56};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_58 = { 1 | NIM_STRLIT_FLAG, ";" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_59 = {1, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_58};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__u89c5Hq4eaoSN9aki1ywKF9aQ_60 = { 2 | NIM_STRLIT_FLAG, "\033\\" };
static const NimStringV2 TM__u89c5Hq4eaoSN9aki1ywKF9aQ_61 = {2, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_60};
N_LIB_PRIVATE NIM_CONST tyArray__Seu7uK9aaOSN0BK3EAjjSHw candidates__kitty95proto_u7 = {{5, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_12},
{7, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_13},
{7, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_14},
{7, (NimStrPayload*)&TM__u89c5Hq4eaoSN9aki1ywKF9aQ_15}}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4183;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4183);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, supportsKittyGraphics__kitty95proto_u5)(void) {
	NIM_BOOL result;
	tyArray__dyW7vpmfeTYw8kX3EXuaJA termVars_1;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 colontmpD__3;
	NimStringV2 colontmpD__4;
	NimStringV2 colontmpD__5;
	NimStringV2 colontmpD__6;
	NimStringV2 T2_;
	NimStringV2 T3_;
	NimStringV2 T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimZeroMem((void*)termVars_1, sizeof(tyArray__dyW7vpmfeTYw8kX3EXuaJA));
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
	colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = getEnv__stdZenvvars_u15(TM__u89c5Hq4eaoSN9aki1ywKF9aQ_3, TM__u89c5Hq4eaoSN9aki1ywKF9aQ_5);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T2_); goto LA1_;}
	termVars_1[0] = T2_;
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_ = getEnv__stdZenvvars_u15(TM__u89c5Hq4eaoSN9aki1ywKF9aQ_7, TM__u89c5Hq4eaoSN9aki1ywKF9aQ_8);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T3_); goto LA1_;}
	termVars_1[1] = T3_;
	T4_.len = 0; T4_.p = NIM_NIL;
	T4_ = getEnv__stdZenvvars_u15(TM__u89c5Hq4eaoSN9aki1ywKF9aQ_10, TM__u89c5Hq4eaoSN9aki1ywKF9aQ_11);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T4_); goto LA1_;}
	termVars_1[2] = T4_;
	{
		NimStringV2 v_1;
		NI i_1;
		v_1.len = 0; v_1.p = NIM_NIL;
		i_1 = ((NI)0);
		{
			while (1) {
				NimStringV2 low_1;
				low_1.len = 0; low_1.p = NIM_NIL;
				eqcopy___system_u2743((&v_1), termVars_1[(i_1)- 0]);
				low_1 = nsuToLowerAsciiStr(v_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
				{
					NimStringV2 name_1;
					NimStringV2 colontmpD__7;
					NI i_2;
					name_1.len = 0; name_1.p = NIM_NIL;
					colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
					colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
					name_1 = colontmpD__7;
					i_2 = ((NI)0);
					{
						while (1) {
							name_1 = candidates__kitty95proto_u7[(i_2)- 0];
							{
								NIM_BOOL T16_;
								T16_ = (NIM_BOOL)0;
								T16_ = contains__pureZstrutils_u1832(low_1, name_1);
								if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
								if (!T16_) goto LA17_;
								result = NIM_TRUE;
								if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
								if (low_1.p && !(low_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(low_1.p);
}
								if (v_1.p && !(v_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(v_1.p);
}
								if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
								if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
								if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
								if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
								if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
								if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
								eqdestroy___pureZstrformat_u492(termVars_1);
								goto BeforeRet_;
							}
LA17_: ;
							{
								if (!(((NI)3) <= i_2)) goto LA21_;
								goto LA12;
							}
LA21_: ;
							i_2 += ((NI)1);
						}
					} LA12: ;
					{
						LA11_:;
					}
					{
						if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
				}
				{
					if (!(((NI)2) <= i_1)) goto LA27_;
					if (low_1.p && !(low_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(low_1.p);
}
					goto LA7;
				}
LA27_: ;
				i_1 += ((NI)1);
				{
					LA9_:;
				}
				{
					if (low_1.p && !(low_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(low_1.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
			}
		} LA7: ;
		{
			LA6_:;
		}
		{
			if (v_1.p && !(v_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(v_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	{
		colontmpD_ = getEnv__stdZenvvars_u15(TM__u89c5Hq4eaoSN9aki1ywKF9aQ_17, TM__u89c5Hq4eaoSN9aki1ywKF9aQ_18);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(((NI)0) < colontmpD_.len)) goto LA35_;
		result = NIM_TRUE;
		if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___pureZstrformat_u492(termVars_1);
		goto BeforeRet_;
	}
LA35_: ;
	{
		NIM_BOOL T39_;
		T39_ = (NIM_BOOL)0;
		colontmpD__2 = getEnv__stdZenvvars_u15(TM__u89c5Hq4eaoSN9aki1ywKF9aQ_20, TM__u89c5Hq4eaoSN9aki1ywKF9aQ_21);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T39_ = (((NI)0) < colontmpD__2.len);
		if (T39_) goto LA40_;
		colontmpD__3 = getEnv__stdZenvvars_u15(TM__u89c5Hq4eaoSN9aki1ywKF9aQ_23, TM__u89c5Hq4eaoSN9aki1ywKF9aQ_24);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T39_ = (((NI)0) < colontmpD__3.len);
LA40_: ;
		if (!T39_) goto LA41_;
		result = NIM_TRUE;
		if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___pureZstrformat_u492(termVars_1);
		goto BeforeRet_;
	}
LA41_: ;
	{
		colontmpD__4 = getEnv__stdZenvvars_u15(TM__u89c5Hq4eaoSN9aki1ywKF9aQ_26, TM__u89c5Hq4eaoSN9aki1ywKF9aQ_27);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(((NI)0) < colontmpD__4.len)) goto LA45_;
		result = NIM_TRUE;
		if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___pureZstrformat_u492(termVars_1);
		goto BeforeRet_;
	}
LA45_: ;
	{
		NIM_BOOL T49_;
		T49_ = (NIM_BOOL)0;
		colontmpD__5 = getEnv__stdZenvvars_u15(TM__u89c5Hq4eaoSN9aki1ywKF9aQ_29, TM__u89c5Hq4eaoSN9aki1ywKF9aQ_30);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T49_ = (((NI)0) < colontmpD__5.len);
		if (T49_) goto LA50_;
		colontmpD__6 = getEnv__stdZenvvars_u15(TM__u89c5Hq4eaoSN9aki1ywKF9aQ_32, TM__u89c5Hq4eaoSN9aki1ywKF9aQ_33);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T49_ = (((NI)0) < colontmpD__6.len);
LA50_: ;
		if (!T49_) goto LA51_;
		result = NIM_TRUE;
		if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___pureZstrformat_u492(termVars_1);
		goto BeforeRet_;
	}
LA51_: ;
	result = NIM_FALSE;
	{
		LA1_:;
	}
	{
		if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___pureZstrformat_u492(termVars_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2492(s_p0);
	}
LA5_: ;
}
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1285)(NimStringV2 s_p0, tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg x_p1) {
	NimStringV2 result;
	NI a_1;
	NI L_1;
	result.len = 0; result.p = NIM_NIL;
	a_1 = x_p1.a;
	L_1 = (NI)((NI)(x_p1.b - a_1) + ((NI)1));
	result = mnewString((L_1));
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < L_1)) goto LA3;
				i_1 = i_2;
				nimPrepareStrMutationV2((&result));
				result.p->data[i_1] = s_p0.p->data[(NI)(i_1 + a_1)];
				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	return result;
}
static N_INLINE(tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1) {
	tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg result;
	result.a = a_p0;
	result.b = b_p1;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, displayKittyGraphics__kitty95proto_u42)(NimStringV2 logoBytes_p0, NI columns_p1, NI rows_p2) {
	NimStringV2 encoded_1;
	NI offset_1;
	NIM_BOOL first_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	encoded_1.len = 0; encoded_1.p = NIM_NIL;
	{
		if (!(logoBytes_p0.len == ((NI)0))) goto LA4_;
		if (encoded_1.p && !(encoded_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(encoded_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	encoded_1 = encode__pureZbase64_u42(((logoBytes_p0).p) ? (logoBytes_p0.p->data) : NIM_NIL, logoBytes_p0.len, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	offset_1 = ((NI)0);
	first_1 = NIM_TRUE;
	{
		while (1) {
			NimStringV2 chunk_1;
			tySequence__sM4lkSb7zS6F7OVMvW9cffQ ctrl_1;
			NimStringV2 colontmpD_;
			NimStringV2 colontmpD__2;
			NI chunkEnd_1;
			tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg T9_;
			NimStringV2 T24_;
			NimStringV2 T25_;
			if (!(offset_1 < encoded_1.len)) goto LA7;
			chunk_1.len = 0; chunk_1.p = NIM_NIL;
			ctrl_1.len = 0; ctrl_1.p = NIM_NIL;
			colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
			chunkEnd_1 = (((NI)(offset_1 + ((NI)4096)) <= encoded_1.len) ? (NI)(offset_1 + ((NI)4096)) : encoded_1.len);
			T9_ = dotdot___stdZstrbasics_u48(offset_1, (NI)(chunkEnd_1 - ((NI)1)));
			chunk_1 = X5BX5D___pureZstrutils_u1285(encoded_1, T9_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			ctrl_1.len = 0; ctrl_1.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
			{
				if (!first_1) goto LA12_;
				add__stdZenumutils_u70((&ctrl_1), TM__u89c5Hq4eaoSN9aki1ywKF9aQ_35);
				add__stdZenumutils_u70((&ctrl_1), TM__u89c5Hq4eaoSN9aki1ywKF9aQ_37);
				add__stdZenumutils_u70((&ctrl_1), TM__u89c5Hq4eaoSN9aki1ywKF9aQ_39);
				add__stdZenumutils_u70((&ctrl_1), TM__u89c5Hq4eaoSN9aki1ywKF9aQ_41);
				add__stdZenumutils_u70((&ctrl_1), TM__u89c5Hq4eaoSN9aki1ywKF9aQ_43);
				{
					NimStringV2 colontmpD__3;
					NimStringV2 T18_;
					if (!(((NI)0) < columns_p1)) goto LA16_;
					colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
					T18_.len = 0; T18_.p = NIM_NIL;
					colontmpD__3 = dollar___systemZdollars_u14(columns_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
					T18_ = rawNewString(colontmpD__3.len + 2);
appendString((&T18_), TM__u89c5Hq4eaoSN9aki1ywKF9aQ_45);
appendString((&T18_), colontmpD__3);
					add__stdZenumutils_u70((&ctrl_1), T18_);
					if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
				}
LA16_: ;
				{
					NimStringV2 colontmpD__4;
					NimStringV2 T23_;
					if (!(((NI)0) < rows_p2)) goto LA21_;
					colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
					T23_.len = 0; T23_.p = NIM_NIL;
					colontmpD__4 = dollar___systemZdollars_u14(rows_p2);
					if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
					T23_ = rawNewString(colontmpD__4.len + 2);
appendString((&T23_), TM__u89c5Hq4eaoSN9aki1ywKF9aQ_47);
appendString((&T23_), colontmpD__4);
					add__stdZenumutils_u70((&ctrl_1), T23_);
					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
				}
LA21_: ;
			}
LA12_: ;
			T24_.len = 0; T24_.p = NIM_NIL;
			T25_.len = 0; T25_.p = NIM_NIL;
			{
				if (!(chunkEnd_1 < encoded_1.len)) goto LA28_;
				colontmpD_ = TM__u89c5Hq4eaoSN9aki1ywKF9aQ_51;
				T25_ = colontmpD_;
			}
			goto LA26_;
LA28_: ;
			{
				colontmpD__2 = TM__u89c5Hq4eaoSN9aki1ywKF9aQ_53;
				T25_ = colontmpD__2;
			}
LA26_: ;
			T24_ = rawNewString(T25_.len + 2);
appendString((&T24_), TM__u89c5Hq4eaoSN9aki1ywKF9aQ_49);
appendString((&T24_), T25_);
			add__stdZenumutils_u70((&ctrl_1), T24_);
			write__stdZsyncio_u254(stdout, TM__u89c5Hq4eaoSN9aki1ywKF9aQ_55);
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			{
				NI T33_;
				NimStringV2 colontmpD__5;
				T33_ = ctrl_1.len;
				if (!(((NI)0) < T33_)) goto LA34_;
				colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
				colontmpD__5 = nsuJoinSep(((ctrl_1).p) ? (ctrl_1.p->data) : NIM_NIL, ctrl_1.len, TM__u89c5Hq4eaoSN9aki1ywKF9aQ_57);
				if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
				write__stdZsyncio_u254(stdout, colontmpD__5);
				if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
				{
					LA36_:;
				}
				{
					if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			}
LA34_: ;
			{
				if (!(((NI)0) < chunk_1.len)) goto LA41_;
				write__stdZsyncio_u254(stdout, TM__u89c5Hq4eaoSN9aki1ywKF9aQ_59);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				write__stdZsyncio_u254(stdout, chunk_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			}
LA41_: ;
			write__stdZsyncio_u254(stdout, TM__u89c5Hq4eaoSN9aki1ywKF9aQ_61);
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			offset_1 = chunkEnd_1;
			first_1 = NIM_FALSE;
			{
				LA8_:;
			}
			{
				if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
				if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				eqdestroy___system_u5543(ctrl_1);
				if (chunk_1.p && !(chunk_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(chunk_1.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		} LA7: ;
	}
	{
		LA1_:;
	}
	{
		if (encoded_1.p && !(encoded_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(encoded_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
