/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@mnymph_settings.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@mnymph_settings.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_RuntimeConfig__a1LTsnph9a3TaW2ET8cuIoA tyObject_RuntimeConfig__a1LTsnph9a3TaW2ET8cuIoA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg tySequence__TM0VfWZgOhRIJ9bpQyFJFrg;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content;
typedef struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_RuntimeConfig__a1LTsnph9a3TaW2ET8cuIoA {
	NI maxLogoWidth;
	NI statsOffset;
	NimStringV2 configLogoDir;
	NimStringV2 customLogoFile;
	NIM_BOOL noColor;
	NimStringV2 theme;
	NimStringV2 iconPack;
	NimStringV2 layout;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ modules;
	NIM_BOOL jsonOutput;
	NimStringV2 loadedConfigPath;
};
struct tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg {
	NI a;
	NI b;
};
typedef NU8 tyEnum_FileMode__Ml1UmeTZyL4qTNLArpZUBA;
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg {
  NI len; tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__TM0VfWZgOhRIJ9bpQyFJFrg trace;
	Exception* up;
};
typedef NimStringV2 tyArray__Seu7uK9aaOSN0BK3EAjjSHw[4];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content { NI cap; tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5543)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, defaultConfig__nymph95settings_u59)(tyObject_RuntimeConfig__a1LTsnph9a3TaW2ET8cuIoA* Result);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, configPaths__nymph95settings_u101)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2740)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normalizeDir__nymph95settings_u17)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2743)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetHomeDir)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2749)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1285)(NimStringV2 s_p0, tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg x_p1);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2492)(NimStringV2* s_p0);
static N_INLINE(tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u88)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, absolutePath__stdZprivateZospaths2_u359)(NimStringV2 path_p0, NimStringV2 root_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetCurrentDir)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename_p0);
N_LIB_PRIVATE N_NIMCALL(FILE*, open__stdZsyncio_u487)(NimStringV2 filename_p0, tyEnum_FileMode__Ml1UmeTZyL4qTNLArpZUBA mode_p1, NI bufSize_p2);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__stdZsyncio_u289)(FILE* f_p0, NimStringV2* line_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringV2 s_p0, NimStringV2 prefix_p1);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitString)(NimStringV2 s_p0, NimStringV2 sep_p1, NI maxsplit_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToLowerAsciiStr)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hashString)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3702)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
static N_INLINE(NIM_BOOL, contains__stdZenumutils_u50)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1);
static N_INLINE(NI, find__stdZenumutils_u55)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u5552)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9036)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u268)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosdirExists)(NimStringV2 dir_p0);
N_LIB_PRIVATE N_NIMCALL(void, noscreateDir)(NimStringV2 dir_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(void, writeFile__stdZsyncio_u534)(NimStringV2 filename_p0, NimStringV2 content_p1);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__oatL38dc1saP5mH5yWvccw_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_3 = {0, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_2};
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_4 = {0, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_2};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__oatL38dc1saP5mH5yWvccw_5 = { 10 | NIM_STRLIT_FLAG, "catppuccin" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_6 = {10, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_5};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__oatL38dc1saP5mH5yWvccw_7 = { 4 | NIM_STRLIT_FLAG, "nerd" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_8 = {4, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_7};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__oatL38dc1saP5mH5yWvccw_9 = { 4 | NIM_STRLIT_FLAG, "full" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_10 = {4, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_9};
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_11 = {0, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_2};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__oatL38dc1saP5mH5yWvccw_12 = { 12 | NIM_STRLIT_FLAG, "NYMPH_CONFIG" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_13 = {12, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_12};
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_14 = {0, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_2};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__oatL38dc1saP5mH5yWvccw_15 = { 15 | NIM_STRLIT_FLAG, "XDG_CONFIG_HOME" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_16 = {15, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_15};
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_17 = {0, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_2};
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_18 = {0, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_2};
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_19 = {0, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_2};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__oatL38dc1saP5mH5yWvccw_20 = { 5 | NIM_STRLIT_FLAG, "nymph" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_21 = {5, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_20};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__oatL38dc1saP5mH5yWvccw_22 = { 11 | NIM_STRLIT_FLAG, "config.conf" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_23 = {11, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_22};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__oatL38dc1saP5mH5yWvccw_24 = { 7 | NIM_STRLIT_FLAG, ".config" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_25 = {7, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_24};
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_26 = {5, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_20};
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_27 = {11, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_22};
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__oatL38dc1saP5mH5yWvccw_28 = { 26 | NIM_STRLIT_FLAG, "/etc/xdg/nymph/config.conf" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_29 = {26, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_28};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__oatL38dc1saP5mH5yWvccw_30 = {
0x00, 0x3e, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__oatL38dc1saP5mH5yWvccw_31 = { 1 | NIM_STRLIT_FLAG, "#" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_32 = {1, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_31};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__oatL38dc1saP5mH5yWvccw_33 = { 1 | NIM_STRLIT_FLAG, "=" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_34 = {1, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_33};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__oatL38dc1saP5mH5yWvccw_35 = {
0x00, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__oatL38dc1saP5mH5yWvccw_36 = { 8 | NIM_STRLIT_FLAG, "maxwidth" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_37 = {8, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_36};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__oatL38dc1saP5mH5yWvccw_38 = { 11 | NIM_STRLIT_FLAG, "statsoffset" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_39 = {11, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_38};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__oatL38dc1saP5mH5yWvccw_40 = { 10 | NIM_STRLIT_FLAG, "customlogo" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_41 = {10, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_40};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__oatL38dc1saP5mH5yWvccw_42 = { 7 | NIM_STRLIT_FLAG, "nocolor" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_43 = {7, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_42};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__oatL38dc1saP5mH5yWvccw_44 = { 5 | NIM_STRLIT_FLAG, "theme" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_45 = {5, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_44};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__oatL38dc1saP5mH5yWvccw_46 = { 8 | NIM_STRLIT_FLAG, "iconpack" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_47 = {8, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_46};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__oatL38dc1saP5mH5yWvccw_48 = { 6 | NIM_STRLIT_FLAG, "layout" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_49 = {6, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_48};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__oatL38dc1saP5mH5yWvccw_50 = { 7 | NIM_STRLIT_FLAG, "modules" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_51 = {7, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_50};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__oatL38dc1saP5mH5yWvccw_52 = { 4 | NIM_STRLIT_FLAG, "json" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_53 = {4, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_52};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__oatL38dc1saP5mH5yWvccw_55 = { 1 | NIM_STRLIT_FLAG, "1" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__oatL38dc1saP5mH5yWvccw_56 = { 4 | NIM_STRLIT_FLAG, "true" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__oatL38dc1saP5mH5yWvccw_57 = { 3 | NIM_STRLIT_FLAG, "yes" };
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__oatL38dc1saP5mH5yWvccw_58 = { 2 | NIM_STRLIT_FLAG, "on" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_59 = {7, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_24};
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_60 = {5, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_20};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__oatL38dc1saP5mH5yWvccw_61 = { 5 | NIM_STRLIT_FLAG, "logos" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_62 = {5, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_61};
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_63 = {11, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_22};
static const struct {
  NI cap; NIM_CHAR data[45+1];
} TM__oatL38dc1saP5mH5yWvccw_64 = { 45 | NIM_STRLIT_FLAG, "# Nymph configuration (key=value)\012maxwidth = " };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_65 = {45, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_64};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__oatL38dc1saP5mH5yWvccw_66 = { 15 | NIM_STRLIT_FLAG, "\012statsoffset = " };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_67 = {15, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_66};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__oatL38dc1saP5mH5yWvccw_68 = { 9 | NIM_STRLIT_FLAG, "\012theme = " };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_69 = {9, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_68};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__oatL38dc1saP5mH5yWvccw_70 = { 12 | NIM_STRLIT_FLAG, "\012iconpack = " };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_71 = {12, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_70};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__oatL38dc1saP5mH5yWvccw_72 = { 10 | NIM_STRLIT_FLAG, "\012layout = " };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_73 = {10, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_72};
static const struct {
  NI cap; NIM_CHAR data[138+1];
} TM__oatL38dc1saP5mH5yWvccw_74 = { 138 | NIM_STRLIT_FLAG, "\012modules = os,kernel,desktop,packages,shell,uptime,memory,colours\012json = false\012nocolor = false\012customlogo = \"\"  # full path to a PNG logo\012" };
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_75 = {138, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_74};
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_76 = {5, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_61};
static const NimStringV2 TM__oatL38dc1saP5mH5yWvccw_77 = {11, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_22};
static NIM_CONST tyArray__Seu7uK9aaOSN0BK3EAjjSHw TM__oatL38dc1saP5mH5yWvccw_54 = {{1, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_55},
{4, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_56},
{3, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_57},
{2, (NimStrPayload*)&TM__oatL38dc1saP5mH5yWvccw_58}}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4183;
extern NIM_THREADVAR Exception* currException__system_u3669;
N_LIB_PRIVATE N_NIMCALL(void, defaultConfig__nymph95settings_u59)(tyObject_RuntimeConfig__a1LTsnph9a3TaW2ET8cuIoA* Result) {
	(*Result).maxLogoWidth = ((NI)200);
	(*Result).statsOffset = ((NI)22);
	(*Result).configLogoDir = TM__oatL38dc1saP5mH5yWvccw_3;
	(*Result).customLogoFile = TM__oatL38dc1saP5mH5yWvccw_4;
	(*Result).noColor = NIM_FALSE;
	(*Result).theme = TM__oatL38dc1saP5mH5yWvccw_6;
	(*Result).iconPack = TM__oatL38dc1saP5mH5yWvccw_8;
	(*Result).layout = TM__oatL38dc1saP5mH5yWvccw_10;
	(*Result).modules.len = 0; (*Result).modules.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	(*Result).jsonOutput = NIM_FALSE;
	(*Result).loadedConfigPath = TM__oatL38dc1saP5mH5yWvccw_11;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___nymph95settings_u77)(tyObject_RuntimeConfig__a1LTsnph9a3TaW2ET8cuIoA* dest_p0, tyObject_RuntimeConfig__a1LTsnph9a3TaW2ET8cuIoA* src_p1) {
	(*dest_p0).maxLogoWidth = (*src_p1).maxLogoWidth;
	(*dest_p0).statsOffset = (*src_p1).statsOffset;
	if ((*dest_p0).configLogoDir.p != (*src_p1).configLogoDir.p) {	if ((*dest_p0).configLogoDir.p && !((*dest_p0).configLogoDir.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).configLogoDir.p);
}
	}
(*dest_p0).configLogoDir.len = (*src_p1).configLogoDir.len; (*dest_p0).configLogoDir.p = (*src_p1).configLogoDir.p;
	if ((*dest_p0).customLogoFile.p != (*src_p1).customLogoFile.p) {	if ((*dest_p0).customLogoFile.p && !((*dest_p0).customLogoFile.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).customLogoFile.p);
}
	}
(*dest_p0).customLogoFile.len = (*src_p1).customLogoFile.len; (*dest_p0).customLogoFile.p = (*src_p1).customLogoFile.p;
	(*dest_p0).noColor = (*src_p1).noColor;
	if ((*dest_p0).theme.p != (*src_p1).theme.p) {	if ((*dest_p0).theme.p && !((*dest_p0).theme.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).theme.p);
}
	}
(*dest_p0).theme.len = (*src_p1).theme.len; (*dest_p0).theme.p = (*src_p1).theme.p;
	if ((*dest_p0).iconPack.p != (*src_p1).iconPack.p) {	if ((*dest_p0).iconPack.p && !((*dest_p0).iconPack.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).iconPack.p);
}
	}
(*dest_p0).iconPack.len = (*src_p1).iconPack.len; (*dest_p0).iconPack.p = (*src_p1).iconPack.p;
	if ((*dest_p0).layout.p != (*src_p1).layout.p) {	if ((*dest_p0).layout.p && !((*dest_p0).layout.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).layout.p);
}
	}
(*dest_p0).layout.len = (*src_p1).layout.len; (*dest_p0).layout.p = (*src_p1).layout.p;
	if ((*dest_p0).modules.p != (*src_p1).modules.p) {	eqdestroy___system_u5543((*dest_p0).modules);
	}
(*dest_p0).modules.len = (*src_p1).modules.len; (*dest_p0).modules.p = (*src_p1).modules.p;
	(*dest_p0).jsonOutput = (*src_p1).jsonOutput;
	if ((*dest_p0).loadedConfigPath.p != (*src_p1).loadedConfigPath.p) {	if ((*dest_p0).loadedConfigPath.p && !((*dest_p0).loadedConfigPath.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).loadedConfigPath.p);
}
	}
(*dest_p0).loadedConfigPath.len = (*src_p1).loadedConfigPath.len; (*dest_p0).loadedConfigPath.p = (*src_p1).loadedConfigPath.p;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2492(s_p0);
	}
LA5_: ;
}
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1285)(NimStringV2 s_p0, tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg x_p1) {
	NimStringV2 result;
	NI a_1;
	NI L_1;
	result.len = 0; result.p = NIM_NIL;
	a_1 = x_p1.a;
	L_1 = (NI)((NI)(x_p1.b - a_1) + ((NI)1));
	result = mnewString((L_1));
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < L_1)) goto LA3;
				i_1 = i_2;
				nimPrepareStrMutationV2((&result));
				result.p->data[i_1] = s_p0.p->data[(NI)(i_1 + a_1)];
				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	return result;
}
static N_INLINE(tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1) {
	tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg result;
	result.a = a_p0;
	result.b = b_p1;
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4183);
	return result;
}
static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u88)(NimStringV2 head_p0, NimStringV2 tail_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = nosjoinPath(head_p0, tail_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normalizeDir__nymph95settings_u17)(NimStringV2 path_p0) {
	NimStringV2 result;
	NimStringV2 expanded_1;
	NimStringV2 T36_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	expanded_1.len = 0; expanded_1.p = NIM_NIL;
	{
		if (!(path_p0.len == ((NI)0))) goto LA4_;
		result = TM__oatL38dc1saP5mH5yWvccw_18;
		if (expanded_1.p && !(expanded_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(expanded_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	eqcopy___system_u2743((&expanded_1), path_p0);
	{
		NimStringV2 home_1;
		if (!((NU8)(expanded_1.p->data[((NI)0)]) == (NU8)(126))) goto LA8_;
		home_1.len = 0; home_1.p = NIM_NIL;
		home_1 = nosgetHomeDir();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		{
			if (!(((NI)0) < home_1.len)) goto LA12_;
			{
				if (!(expanded_1.len == ((NI)1))) goto LA16_;
				eqsink___system_u2749((&expanded_1), home_1);
				eqwasMoved___system_u2740((&home_1));
			}
			goto LA14_;
LA16_: ;
			{
				NimStringV2 suffix_1;
				tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg T19_;
				NimStringV2 T35_;
				suffix_1.len = 0; suffix_1.p = NIM_NIL;
				T19_ = dotdot___stdZstrbasics_u48(((NI)1), (expanded_1.len-1));
				suffix_1 = X5BX5D___pureZstrutils_u1285(expanded_1, T19_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				{
					NIM_BOOL T22_;
					NIM_BOOL T24_;
					T22_ = (NIM_BOOL)0;
					T22_ = (((NI)0) < suffix_1.len);
					if (!(T22_)) goto LA23_;
					T24_ = (NIM_BOOL)0;
					T24_ = ((NU8)(suffix_1.p->data[((NI)0)]) == (NU8)(47));
					if (T24_) goto LA25_;
					T24_ = ((NU8)(suffix_1.p->data[((NI)0)]) == (NU8)(47));
LA25_: ;
					T22_ = T24_;
LA23_: ;
					if (!T22_) goto LA26_;
					{
						tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg T32_;
						NimStringV2 T33_;
						if (!(((NI)1) < suffix_1.len)) goto LA30_;
						T32_ = dotdot___stdZstrbasics_u48(((NI)1), (suffix_1.len-1));
						T33_.len = 0; T33_.p = NIM_NIL;
						T33_ = X5BX5D___pureZstrutils_u1285(suffix_1, T32_);
						if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T33_); goto LA1_;}
						eqsink___system_u2749((&suffix_1), T33_);
					}
					goto LA28_;
LA30_: ;
					{
						eqsink___system_u2749((&suffix_1), TM__oatL38dc1saP5mH5yWvccw_19);
					}
LA28_: ;
				}
LA26_: ;
				T35_.len = 0; T35_.p = NIM_NIL;
				T35_ = slash___stdZprivateZospaths2_u88(home_1, suffix_1);
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T35_); goto LA1_;}
				eqsink___system_u2749((&expanded_1), T35_);
				if (suffix_1.p && !(suffix_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(suffix_1.p);
}
			}
LA14_: ;
		}
LA12_: ;
		if (home_1.p && !(home_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(home_1.p);
}
	}
LA8_: ;
	T36_.len = 0; T36_.p = NIM_NIL;
	{
		NIM_BOOL T39_;
		T39_ = (NIM_BOOL)0;
		T39_ = nosisAbsolute(expanded_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!T39_) goto LA40_;
		result = expanded_1;
		eqwasMoved___system_u2740((&expanded_1));
	}
	goto LA37_;
LA40_: ;
	{
		NimStringV2 colontmpD_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD_ = nosgetCurrentDir();
		if (NIM_UNLIKELY(*nimErr_)) goto LA43_;
		result = absolutePath__stdZprivateZospaths2_u359(expanded_1, colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA43_;
		{
			LA43_:;
		}
		{
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA37_: ;
	{
		LA1_:;
	}
	{
		if (expanded_1.p && !(expanded_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(expanded_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, configPaths__nymph95settings_u101)(void) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
	NimStringV2 envCfg_1;
	NimStringV2 xdg_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	envCfg_1.len = 0; envCfg_1.p = NIM_NIL;
	xdg_1.len = 0; xdg_1.p = NIM_NIL;
	envCfg_1 = getEnv__stdZenvvars_u15(TM__oatL38dc1saP5mH5yWvccw_13, TM__oatL38dc1saP5mH5yWvccw_14);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NimStringV2 blitTmp_1;
		if (!(((NI)0) < envCfg_1.len)) goto LA4_;
		blitTmp_1 = envCfg_1;
		eqwasMoved___system_u2740((&envCfg_1));
		add__stdZenumutils_u70((&result), blitTmp_1);
	}
LA4_: ;
	xdg_1 = getEnv__stdZenvvars_u15(TM__oatL38dc1saP5mH5yWvccw_16, TM__oatL38dc1saP5mH5yWvccw_17);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		NimStringV2 T11_;
		if (!(((NI)0) < xdg_1.len)) goto LA8_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		colontmpD_ = slash___stdZprivateZospaths2_u88(xdg_1, TM__oatL38dc1saP5mH5yWvccw_21);
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		colontmpD__2 = slash___stdZprivateZospaths2_u88(colontmpD_, TM__oatL38dc1saP5mH5yWvccw_23);
		if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
		T11_.len = 0; T11_.p = NIM_NIL;
		T11_ = normalizeDir__nymph95settings_u17(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T11_); goto LA10_;}
		add__stdZenumutils_u70((&result), T11_);
		{
			LA10_:;
		}
		{
			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA6_;
LA8_: ;
	{
		NimStringV2 colontmpD__3;
		NimStringV2 colontmpD__4;
		NimStringV2 colontmpD__5;
		NimStringV2 colontmpD__6;
		NimStringV2 T16_;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
		colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
		colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
		colontmpD__3 = nosgetHomeDir();
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		colontmpD__4 = slash___stdZprivateZospaths2_u88(colontmpD__3, TM__oatL38dc1saP5mH5yWvccw_25);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		colontmpD__5 = slash___stdZprivateZospaths2_u88(colontmpD__4, TM__oatL38dc1saP5mH5yWvccw_26);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		colontmpD__6 = slash___stdZprivateZospaths2_u88(colontmpD__5, TM__oatL38dc1saP5mH5yWvccw_27);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		T16_.len = 0; T16_.p = NIM_NIL;
		T16_ = normalizeDir__nymph95settings_u17(colontmpD__6);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T16_); goto LA15_;}
		add__stdZenumutils_u70((&result), T16_);
		{
			LA15_:;
		}
		{
			if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
			if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
			if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA6_: ;
	add__stdZenumutils_u70((&result), TM__oatL38dc1saP5mH5yWvccw_29);
	{
		LA1_:;
	}
	{
		if (xdg_1.p && !(xdg_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(xdg_1.p);
}
		if (envCfg_1.p && !(envCfg_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(envCfg_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
{	result = NIM_FALSE;
	alen_1 = a_p0.len;
	blen_1 = b_p1.len;
	{
		if (!(alen_1 == blen_1)) goto LA3_;
		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = currException__system_u3669;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3702(&currException__system_u3669, (*currException__system_u3669).up, NIM_FALSE);
}
static N_INLINE(NI, find__stdZenumutils_u55)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1) {
	NI result;
{	result = ((NI)0);
	{
		NimStringV2* i_1;
		NI i_2;
		i_1 = (NimStringV2*)0;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < a_p0Len_0)) goto LA3;
				i_1 = (&a_p0[i_2]);
				{
					if (!eqStrings((*i_1), item_p1)) goto LA6_;
					goto BeforeRet_;
				}
LA6_: ;
				result += ((NI)1);
				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	result = ((NI)-1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, contains__stdZenumutils_u50)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1) {
	NIM_BOOL result;
	NI T1_;
{	T1_ = (NI)0;
	T1_ = find__stdZenumutils_u55(a_p0, a_p0Len_0, item_p1);
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, loadConfig__nymph95settings_u121)(tyObject_RuntimeConfig__a1LTsnph9a3TaW2ET8cuIoA* Result) {
	NimStringV2 homeCfg_1;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 colontmpD__3;
	NIM_BOOL found_1;
NIM_BOOL oldNimErrFin17_;
	NimStringV2 T158_;
	NimStringV2 T159_;
	NimStringV2 T160_;
	NimStringV2 T161_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_RuntimeConfig__a1LTsnph9a3TaW2ET8cuIoA));
	homeCfg_1.len = 0; homeCfg_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	defaultConfig__nymph95settings_u59(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	found_1 = NIM_FALSE;
	{
		tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmp_;
		NimStringV2* path_1;
		NI i_1;
		NI L_1;
		NI T4_;
		colontmp_.len = 0; colontmp_.p = NIM_NIL;
		path_1 = (NimStringV2*)0;
		colontmp_ = configPaths__nymph95settings_u101();
		if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
		i_1 = ((NI)0);
		T4_ = colontmp_.len;
		L_1 = T4_;
		{
			while (1) {
				if (!(i_1 < L_1)) goto LA6;
				path_1 = (&colontmp_.p->data[i_1]);
				{
					{
						NIM_BOOL T10_;
						T10_ = (NIM_BOOL)0;
						T10_ = nosfileExists((*path_1));
						if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
						if (!!(T10_)) goto LA11_;
						goto LA7;
					}
LA11_: ;
					{
						NimStringV2 rawLine_1;
						NimStringV2 colontmpD__4;
						FILE* f_1;
						FILE* T16_;
						NimStringV2 res_1;
						rawLine_1.len = 0; rawLine_1.p = NIM_NIL;
						colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
						colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
						rawLine_1 = colontmpD__4;
						T16_ = (FILE*)0;
						T16_ = open__stdZsyncio_u487((*path_1), ((tyEnum_FileMode__Ml1UmeTZyL4qTNLArpZUBA)0), ((NI)8000));
						if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
						f_1 = T16_;
						res_1.len = 0; res_1.p = NIM_NIL;
						res_1 = rawNewString(((NI)80));
						{
							while (1) {
								NIM_BOOL T21_;
								T21_ = (NIM_BOOL)0;
								T21_ = readLine__stdZsyncio_u289(f_1, (&res_1));
								if (NIM_UNLIKELY(*nimErr_)) goto LA18_;
								if (!T21_) goto LA20;
								rawLine_1 = res_1;
								{
									NimStringV2 line_1;
									tySequence__sM4lkSb7zS6F7OVMvW9cffQ parts_1;
									NimStringV2 key_1;
									NimStringV2 colontmpD__5;
									NimStringV2 val_1;
									NimStringV2 T24_;
									NI hashPos_1;
									NI T31_;
									tySequence__sM4lkSb7zS6F7OVMvW9cffQ T46_;
									NimStringV2 T52_;
									NimStringV2 T53_;
									NimStringV2 T54_;
									NimStringV2 T55_;
									line_1.len = 0; line_1.p = NIM_NIL;
									parts_1.len = 0; parts_1.p = NIM_NIL;
									key_1.len = 0; key_1.p = NIM_NIL;
									colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
									val_1.len = 0; val_1.p = NIM_NIL;
									T24_.len = 0; T24_.p = NIM_NIL;
									T24_ = nsuStrip(rawLine_1, NIM_TRUE, NIM_TRUE, TM__oatL38dc1saP5mH5yWvccw_30);
									if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T24_); goto LA23_;}
									line_1 = T24_;
									{
										NIM_BOOL T27_;
										T27_ = (NIM_BOOL)0;
										T27_ = (line_1.len == ((NI)0));
										if (T27_) goto LA28_;
										T27_ = nsuStartsWith(line_1, TM__oatL38dc1saP5mH5yWvccw_32);
										if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
LA28_: ;
										if (!T27_) goto LA29_;
										if (val_1.p && !(val_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(val_1.p);
}
										if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
										if (key_1.p && !(key_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(key_1.p);
}
										eqdestroy___system_u5543(parts_1);
										if (line_1.p && !(line_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(line_1.p);
}
										goto LA22;
									}
LA29_: ;
									T31_ = (NI)0;
									T31_ = nsuFindChar(line_1, 35, ((NI)0), ((NI)-1));
									if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
									hashPos_1 = T31_;
									{
										NimStringV2 colontmpD__6;
										tyObject_HSlice__kKkMVftCLYDJiTZe9bGlLsg T37_;
										NimStringV2 T38_;
										NimStringV2 T39_;
										if (!(((NI)0) <= hashPos_1)) goto LA34_;
										colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
										T37_ = dotdot___stdZstrbasics_u48(((NI)0), (NI)(hashPos_1 - ((NI)1)));
										T38_.len = 0; T38_.p = NIM_NIL;
										T38_ = X5BX5D___pureZstrutils_u1285(line_1, T37_);
										if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T38_); goto LA36_;}
										colontmpD__6 = T38_;
										T39_.len = 0; T39_.p = NIM_NIL;
										T39_ = nsuStrip(colontmpD__6, NIM_TRUE, NIM_TRUE, TM__oatL38dc1saP5mH5yWvccw_30);
										if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T39_); goto LA36_;}
										eqsink___system_u2749((&line_1), T39_);
										{
											if (!(line_1.len == ((NI)0))) goto LA42_;
											if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
											if (val_1.p && !(val_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(val_1.p);
}
											if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
											if (key_1.p && !(key_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(key_1.p);
}
											eqdestroy___system_u5543(parts_1);
											if (line_1.p && !(line_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(line_1.p);
}
											goto LA22;
										}
LA42_: ;
										{
											LA36_:;
										}
										{
											if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
										}
										if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
									}
LA34_: ;
									T46_.len = 0; T46_.p = NIM_NIL;
									T46_ = nsuSplitString(line_1, TM__oatL38dc1saP5mH5yWvccw_34, ((NI)1));
									if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u5543(T46_); goto LA23_;}
									parts_1 = T46_;
									{
										NI T49_;
										T49_ = parts_1.len;
										if (!!((T49_ == ((NI)2)))) goto LA50_;
										if (val_1.p && !(val_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(val_1.p);
}
										if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
										if (key_1.p && !(key_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(key_1.p);
}
										eqdestroy___system_u5543(parts_1);
										if (line_1.p && !(line_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(line_1.p);
}
										goto LA22;
									}
LA50_: ;
									T52_.len = 0; T52_.p = NIM_NIL;
									T52_ = nsuStrip(parts_1.p->data[((NI)0)], NIM_TRUE, NIM_TRUE, TM__oatL38dc1saP5mH5yWvccw_30);
									if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T52_); goto LA23_;}
									colontmpD__5 = T52_;
									T53_.len = 0; T53_.p = NIM_NIL;
									T53_ = nsuToLowerAsciiStr(colontmpD__5);
									if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T53_); goto LA23_;}
									key_1 = T53_;
									T54_.len = 0; T54_.p = NIM_NIL;
									T54_ = nsuStrip(parts_1.p->data[((NI)1)], NIM_TRUE, NIM_TRUE, TM__oatL38dc1saP5mH5yWvccw_30);
									if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T54_); goto LA23_;}
									val_1 = T54_;
									T55_.len = 0; T55_.p = NIM_NIL;
									T55_ = nsuStrip(val_1, NIM_TRUE, NIM_TRUE, TM__oatL38dc1saP5mH5yWvccw_35);
									if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T55_); goto LA23_;}
									eqsink___system_u2749((&val_1), T55_);
									switch (hashString(key_1) & 15) {
									case 0: 
if (eqStrings(key_1, TM__oatL38dc1saP5mH5yWvccw_41)) goto LA58_;
break;
									case 2: 
if (eqStrings(key_1, TM__oatL38dc1saP5mH5yWvccw_37)) goto LA56_;
break;
									case 4: 
if (eqStrings(key_1, TM__oatL38dc1saP5mH5yWvccw_39)) goto LA57_;
break;
									case 7: 
if (eqStrings(key_1, TM__oatL38dc1saP5mH5yWvccw_45)) goto LA60_;
if (eqStrings(key_1, TM__oatL38dc1saP5mH5yWvccw_53)) goto LA64_;
break;
									case 9: 
if (eqStrings(key_1, TM__oatL38dc1saP5mH5yWvccw_49)) goto LA62_;
break;
									case 10: 
if (eqStrings(key_1, TM__oatL38dc1saP5mH5yWvccw_51)) goto LA63_;
break;
									case 11: 
if (eqStrings(key_1, TM__oatL38dc1saP5mH5yWvccw_43)) goto LA59_;
if (eqStrings(key_1, TM__oatL38dc1saP5mH5yWvccw_47)) goto LA61_;
break;
									}
									goto LA65_;
									LA56_: ;
									{
										NI v_1;
										NI T69_;
										T69_ = (NI)0;
										T69_ = nsuParseInt(val_1);
										if (NIM_UNLIKELY(*nimErr_)) goto LA68_;
										v_1 = T69_;
										{
											if (!(((NI)0) < v_1)) goto LA72_;
											(*Result).maxLogoWidth = v_1;
										}
LA72_: ;
										if (NIM_UNLIKELY(*nimErr_)) {
											LA68_:;
											if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 428396544)) {
												*nimErr_ = NIM_FALSE;
												popCurrentException();
												LA75_:;
											}
										}
										if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
									}
									goto LA66_;
									LA57_: ;
									{
										NI v_2;
										NI T79_;
										T79_ = (NI)0;
										T79_ = nsuParseInt(val_1);
										if (NIM_UNLIKELY(*nimErr_)) goto LA78_;
										v_2 = T79_;
										{
											if (!(((NI)0) < v_2)) goto LA82_;
											(*Result).statsOffset = v_2;
										}
LA82_: ;
										if (NIM_UNLIKELY(*nimErr_)) {
											LA78_:;
											if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 428396544)) {
												*nimErr_ = NIM_FALSE;
												popCurrentException();
												LA85_:;
											}
										}
										if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
									}
									goto LA66_;
									LA58_: ;
									{
										{
											if (!(((NI)0) < val_1.len)) goto LA90_;
											eqsink___system_u2749((&(*Result).customLogoFile), val_1);
											eqwasMoved___system_u2740((&val_1));
										}
LA90_: ;
									}
									goto LA66_;
									LA59_: ;
									{
										NimStringV2 colontmpD__7;
										NimStringV2 T93_;
										colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
										T93_.len = 0; T93_.p = NIM_NIL;
										T93_ = nsuToLowerAsciiStr(val_1);
										if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T93_); goto LA23_;}
										colontmpD__7 = T93_;
										(*Result).noColor = contains__stdZenumutils_u50(TM__oatL38dc1saP5mH5yWvccw_54, 4, colontmpD__7);
										if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
									}
									goto LA66_;
									LA60_: ;
									{
										{
											NimStringV2 T99_;
											if (!(((NI)0) < val_1.len)) goto LA97_;
											T99_.len = 0; T99_.p = NIM_NIL;
											T99_ = nsuToLowerAsciiStr(val_1);
											if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T99_); goto LA23_;}
											eqsink___system_u2749((&(*Result).theme), T99_);
										}
LA97_: ;
									}
									goto LA66_;
									LA61_: ;
									{
										{
											NimStringV2 T105_;
											if (!(((NI)0) < val_1.len)) goto LA103_;
											T105_.len = 0; T105_.p = NIM_NIL;
											T105_ = nsuToLowerAsciiStr(val_1);
											if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T105_); goto LA23_;}
											eqsink___system_u2749((&(*Result).iconPack), T105_);
										}
LA103_: ;
									}
									goto LA66_;
									LA62_: ;
									{
										{
											NimStringV2 T111_;
											if (!(((NI)0) < val_1.len)) goto LA109_;
											T111_.len = 0; T111_.p = NIM_NIL;
											T111_ = nsuToLowerAsciiStr(val_1);
											if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T111_); goto LA23_;}
											eqsink___system_u2749((&(*Result).layout), T111_);
										}
LA109_: ;
									}
									goto LA66_;
									LA63_: ;
									{
										tySequence__sM4lkSb7zS6F7OVMvW9cffQ T113_;
										T113_.len = 0; T113_.p = NIM_NIL;
										T113_.len = 0; T113_.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
										eqsink___system_u5552((&(*Result).modules), T113_);
										{
											NimStringV2 rawMod_1;
											NI lastX60gensym34__1;
											NI splitsX60gensym34__1;
											rawMod_1.len = 0; rawMod_1.p = NIM_NIL;
											rawMod_1.len = 0; rawMod_1.p = NIM_NIL;
											lastX60gensym34__1 = ((NI)0);
											splitsX60gensym34__1 = ((NI)-1);
											{
												while (1) {
													NimStringV2 modName_1;
													NimStringV2 colontmpD__8;
													NI firstX60gensym34__1;
													NimStringV2 T127_;
													NimStringV2 T128_;
													NimStringV2 T129_;
													if (!(lastX60gensym34__1 <= val_1.len)) goto LA117;
													modName_1.len = 0; modName_1.p = NIM_NIL;
													colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
													firstX60gensym34__1 = lastX60gensym34__1;
													{
														while (1) {
															NIM_BOOL T121_;
															T121_ = (NIM_BOOL)0;
															T121_ = (lastX60gensym34__1 < val_1.len);
															if (!(T121_)) goto LA122_;
															T121_ = !(((NU8)(val_1.p->data[lastX60gensym34__1]) == (NU8)(44)));
LA122_: ;
															if (!T121_) goto LA120;
															lastX60gensym34__1 += ((NI)1);
														} LA120: ;
													}
													{
														if (!(splitsX60gensym34__1 == ((NI)0))) goto LA125_;
														lastX60gensym34__1 = val_1.len;
													}
LA125_: ;
													T127_.len = 0; T127_.p = NIM_NIL;
													T127_ = substr__system_u9036(val_1, firstX60gensym34__1, (NI)(lastX60gensym34__1 - ((NI)1)));
													eqsink___system_u2749((&rawMod_1), T127_);
													T128_.len = 0; T128_.p = NIM_NIL;
													T128_ = nsuStrip(rawMod_1, NIM_TRUE, NIM_TRUE, TM__oatL38dc1saP5mH5yWvccw_30);
													if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T128_); goto LA118_;}
													colontmpD__8 = T128_;
													T129_.len = 0; T129_.p = NIM_NIL;
													T129_ = nsuToLowerAsciiStr(colontmpD__8);
													if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T129_); goto LA118_;}
													modName_1 = T129_;
													{
														NimStringV2 blitTmp_1;
														if (!(((NI)0) < modName_1.len)) goto LA132_;
														blitTmp_1 = modName_1;
														eqwasMoved___system_u2740((&modName_1));
														add__stdZenumutils_u70((&(*Result).modules), blitTmp_1);
													}
LA132_: ;
													{
														if (!(splitsX60gensym34__1 == ((NI)0))) goto LA136_;
														if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
														if (modName_1.p && !(modName_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(modName_1.p);
}
														goto LA116;
													}
LA136_: ;
													splitsX60gensym34__1 -= ((NI)1);
													lastX60gensym34__1 += ((NI)1);
													{
														LA118_:;
													}
													{
														if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
														if (modName_1.p && !(modName_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(modName_1.p);
}
													}
													if (NIM_UNLIKELY(*nimErr_)) goto LA115_;
												} LA117: ;
											} LA116: ;
											{
												LA115_:;
											}
											{
												if (rawMod_1.p && !(rawMod_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(rawMod_1.p);
}
											}
											if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
										}
									}
									goto LA66_;
									LA64_: ;
									{
										NimStringV2 colontmpD__9;
										NimStringV2 T143_;
										colontmpD__9.len = 0; colontmpD__9.p = NIM_NIL;
										T143_.len = 0; T143_.p = NIM_NIL;
										T143_ = nsuToLowerAsciiStr(val_1);
										if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T143_); goto LA23_;}
										colontmpD__9 = T143_;
										(*Result).jsonOutput = contains__stdZenumutils_u50(TM__oatL38dc1saP5mH5yWvccw_54, 4, colontmpD__9);
										if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
									}
									goto LA66_;
									LA65_: ;
									{
									}
LA66_: ;
									{
										LA23_:;
									}
									{
										if (val_1.p && !(val_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(val_1.p);
}
										if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
										if (key_1.p && !(key_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(key_1.p);
}
										eqdestroy___system_u5543(parts_1);
										if (line_1.p && !(line_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(line_1.p);
}
									}
									if (NIM_UNLIKELY(*nimErr_)) goto LA18_;
								} LA22: ;
							} LA20: ;
						}
						{
							LA18_:;
						}
						{
							if (res_1.p && !(res_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(res_1.p);
}
						}
						if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
						{
							LA17_:;
						}
						{
							oldNimErrFin17_ = *nimErr_; *nimErr_ = NIM_FALSE;
							close__stdZsyncio_u268(f_1);
							if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
							*nimErr_ = oldNimErrFin17_;
						}
						if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
						{
							LA15_:;
						}
						{
							if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
						}
						if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
					}
					eqcopy___system_u2743((&(*Result).loadedConfigPath), (*path_1));
					found_1 = NIM_TRUE;
					if (NIM_UNLIKELY(*nimErr_)) {
						LA13_:;
						if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 1901328640)) {
							*nimErr_ = NIM_FALSE;
							popCurrentException();
							LA154_:;
						}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
				} LA7: ;
				i_1 += ((NI)1);
			} LA6: ;
		}
		{
			LA3_:;
		}
		{
			eqdestroy___system_u5543(colontmp_);
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	T158_.len = 0; T158_.p = NIM_NIL;
	T158_ = nosgetHomeDir();
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T158_); goto LA1_;}
	colontmpD_ = T158_;
	T159_.len = 0; T159_.p = NIM_NIL;
	T159_ = slash___stdZprivateZospaths2_u88(colontmpD_, TM__oatL38dc1saP5mH5yWvccw_59);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T159_); goto LA1_;}
	colontmpD__2 = T159_;
	T160_.len = 0; T160_.p = NIM_NIL;
	T160_ = slash___stdZprivateZospaths2_u88(colontmpD__2, TM__oatL38dc1saP5mH5yWvccw_60);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T160_); goto LA1_;}
	colontmpD__3 = T160_;
	T161_.len = 0; T161_.p = NIM_NIL;
	T161_ = normalizeDir__nymph95settings_u17(colontmpD__3);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T161_); goto LA1_;}
	homeCfg_1 = T161_;
	{
		NimStringV2 logoDir_1;
		NimStringV2 path_2;
		NimStringV2 T173_;
		NimStringV2 T179_;
		if (!!(found_1)) goto LA164_;
		logoDir_1.len = 0; logoDir_1.p = NIM_NIL;
		path_2.len = 0; path_2.p = NIM_NIL;
		{
			NIM_BOOL T170_;
			T170_ = (NIM_BOOL)0;
			T170_ = nosdirExists(homeCfg_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA167_;
			if (!!(T170_)) goto LA171_;
			noscreateDir(homeCfg_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA167_;
		}
LA171_: ;
		T173_.len = 0; T173_.p = NIM_NIL;
		T173_ = slash___stdZprivateZospaths2_u88(homeCfg_1, TM__oatL38dc1saP5mH5yWvccw_62);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T173_); goto LA167_;}
		logoDir_1 = T173_;
		{
			NIM_BOOL T176_;
			T176_ = (NIM_BOOL)0;
			T176_ = nosdirExists(logoDir_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA167_;
			if (!!(T176_)) goto LA177_;
			noscreateDir(logoDir_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA167_;
		}
LA177_: ;
		eqsink___system_u2749((&(*Result).configLogoDir), logoDir_1);
		eqwasMoved___system_u2740((&logoDir_1));
		T179_.len = 0; T179_.p = NIM_NIL;
		T179_ = slash___stdZprivateZospaths2_u88(homeCfg_1, TM__oatL38dc1saP5mH5yWvccw_63);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T179_); goto LA167_;}
		path_2 = T179_;
		eqcopy___system_u2743((&(*Result).loadedConfigPath), path_2);
		{
			NIM_BOOL T182_;
			NimStringV2 content_1;
			NimStringV2 colontmpD__10;
			NimStringV2 colontmpD__11;
			NimStringV2 T186_;
			NimStringV2 T187_;
			NimStringV2 T188_;
			T182_ = (NIM_BOOL)0;
			T182_ = nosfileExists(path_2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA167_;
			if (!!(T182_)) goto LA183_;
			content_1.len = 0; content_1.p = NIM_NIL;
			colontmpD__10.len = 0; colontmpD__10.p = NIM_NIL;
			colontmpD__11.len = 0; colontmpD__11.p = NIM_NIL;
			T186_.len = 0; T186_.p = NIM_NIL;
			T187_.len = 0; T187_.p = NIM_NIL;
			T187_ = dollar___systemZdollars_u14((*Result).maxLogoWidth);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T187_); goto LA185_;}
			colontmpD__10 = T187_;
			T188_.len = 0; T188_.p = NIM_NIL;
			T188_ = dollar___systemZdollars_u14((*Result).statsOffset);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T188_); goto LA185_;}
			colontmpD__11 = T188_;
			T186_ = rawNewString(colontmpD__10.len + colontmpD__11.len + (*Result).theme.len + (*Result).iconPack.len + (*Result).layout.len + 229);
appendString((&T186_), TM__oatL38dc1saP5mH5yWvccw_65);
appendString((&T186_), colontmpD__10);
appendString((&T186_), TM__oatL38dc1saP5mH5yWvccw_67);
appendString((&T186_), colontmpD__11);
appendString((&T186_), TM__oatL38dc1saP5mH5yWvccw_69);
appendString((&T186_), (*Result).theme);
appendString((&T186_), TM__oatL38dc1saP5mH5yWvccw_71);
appendString((&T186_), (*Result).iconPack);
appendString((&T186_), TM__oatL38dc1saP5mH5yWvccw_73);
appendString((&T186_), (*Result).layout);
appendString((&T186_), TM__oatL38dc1saP5mH5yWvccw_75);
			content_1 = T186_;
			writeFile__stdZsyncio_u534(path_2, content_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA185_;
			{
				LA185_:;
			}
			{
				if (colontmpD__11.p && !(colontmpD__11.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__11.p);
}
				if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
				if (content_1.p && !(content_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(content_1.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA167_;
		}
LA183_: ;
		{
			LA167_:;
		}
		{
			if (path_2.p && !(path_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_2.p);
}
			if (logoDir_1.p && !(logoDir_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(logoDir_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA166_;
		if (NIM_UNLIKELY(*nimErr_)) {
			LA166_:;
			if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 1901328640)) {
				*nimErr_ = NIM_FALSE;
				popCurrentException();
				LA194_:;
			}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA162_;
LA164_: ;
	{
		NimStringV2 logoDir_2;
		NimStringV2 T199_;
		logoDir_2.len = 0; logoDir_2.p = NIM_NIL;
		T199_.len = 0; T199_.p = NIM_NIL;
		T199_ = slash___stdZprivateZospaths2_u88(homeCfg_1, TM__oatL38dc1saP5mH5yWvccw_76);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T199_); goto LA198_;}
		logoDir_2 = T199_;
		{
			NIM_BOOL T202_;
			T202_ = (NIM_BOOL)0;
			T202_ = nosdirExists(logoDir_2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA198_;
			if (!!(T202_)) goto LA203_;
			noscreateDir(logoDir_2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA198_;
		}
LA203_: ;
		{
			NIM_BOOL T207_;
			T207_ = (NIM_BOOL)0;
			T207_ = nosdirExists(logoDir_2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA198_;
			if (!T207_) goto LA208_;
			eqsink___system_u2749((&(*Result).configLogoDir), logoDir_2);
			eqwasMoved___system_u2740((&logoDir_2));
		}
LA208_: ;
		{
			NimStringV2 T214_;
			if (!((*Result).loadedConfigPath.len == ((NI)0))) goto LA212_;
			T214_.len = 0; T214_.p = NIM_NIL;
			T214_ = slash___stdZprivateZospaths2_u88(homeCfg_1, TM__oatL38dc1saP5mH5yWvccw_77);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T214_); goto LA198_;}
			eqsink___system_u2749((&(*Result).loadedConfigPath), T214_);
		}
LA212_: ;
		{
			LA198_:;
		}
		{
			if (logoDir_2.p && !(logoDir_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(logoDir_2.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA197_;
		if (NIM_UNLIKELY(*nimErr_)) {
			LA197_:;
			if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 1901328640)) {
				*nimErr_ = NIM_FALSE;
				popCurrentException();
				LA218_:;
			}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA162_: ;
	{
		LA1_:;
	}
	{
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (homeCfg_1.p && !(homeCfg_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(homeCfg_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___nymph95settings_u68)(tyObject_RuntimeConfig__a1LTsnph9a3TaW2ET8cuIoA* dest_p0) {
	if ((*dest_p0).loadedConfigPath.p && !((*dest_p0).loadedConfigPath.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).loadedConfigPath.p);
}
	eqdestroy___system_u5543((*dest_p0).modules);
	if ((*dest_p0).layout.p && !((*dest_p0).layout.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).layout.p);
}
	if ((*dest_p0).iconPack.p && !((*dest_p0).iconPack.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).iconPack.p);
}
	if ((*dest_p0).theme.p && !((*dest_p0).theme.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).theme.p);
}
	if ((*dest_p0).customLogoFile.p && !((*dest_p0).customLogoFile.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).customLogoFile.p);
}
	if ((*dest_p0).configLogoDir.p && !((*dest_p0).configLogoDir.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).configLogoDir.p);
}
}
