/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@palgorithm.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@palgorithm.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NIMCALL(void, fill__pureZstrutils_u1566)(NI* a_p0, NI a_p0Len_0, NI value_p1) {
	NI xX60gensym161__1;
	xX60gensym161__1 = ((NI)0);
	{
		while (1) {
			if (!(xX60gensym161__1 <= (a_p0Len_0-1))) goto LA2;
			a_p0[xX60gensym161__1] = value_p1;
			xX60gensym161__1 += ((NI)1);
		} LA2: ;
	}
}
