/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pbase64.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pbase64.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NIM_CHAR tyArray__o9aRz9a9a9bzfUdxgetJHLgorg[64];
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2492)(NimStringV2* s_p0);
N_LIB_PRIVATE NIM_CONST tyArray__o9aRz9a9a9bzfUdxgetJHLgorg cb64safe__pureZbase64_u5 = {65,
66,
67,
68,
69,
70,
71,
72,
73,
74,
75,
76,
77,
78,
79,
80,
81,
82,
83,
84,
85,
86,
87,
88,
89,
90,
97,
98,
99,
100,
101,
102,
103,
104,
105,
106,
107,
108,
109,
110,
111,
112,
113,
114,
115,
116,
117,
118,
119,
120,
121,
122,
48,
49,
50,
51,
52,
53,
54,
55,
56,
57,
45,
95}
;
N_LIB_PRIVATE NIM_CONST tyArray__o9aRz9a9a9bzfUdxgetJHLgorg cb64__pureZbase64_u4 = {65,
66,
67,
68,
69,
70,
71,
72,
73,
74,
75,
76,
77,
78,
79,
80,
81,
82,
83,
84,
85,
86,
87,
88,
89,
90,
97,
98,
99,
100,
101,
102,
103,
104,
105,
106,
107,
108,
109,
110,
111,
112,
113,
114,
115,
116,
117,
118,
119,
120,
121,
122,
48,
49,
50,
51,
52,
53,
54,
55,
56,
57,
43,
47}
;
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2492(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, encode__pureZbase64_u42)(NIM_CHAR* s_p0, NI s_p0Len_0, NIM_BOOL safe_p1) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	{
		NI paddingX60gensym4__1;
		NI inputEndsX60gensym4__1;
		NI inputIndexX60gensym4__1;
		NI outputIndexX60gensym4__1;
		NU32 nX60gensym4__1;
		NU32 bX60gensym4__1;
		if (!safe_p1) goto LA3_;
		setLengthStrV2((&result), ((NI)((NI)((NI)(s_p0Len_0 / ((NI)3)) + s_p0Len_0) + ((NI)6))));
		paddingX60gensym4__1 = (NI)(s_p0Len_0 % ((NI)3));
		inputEndsX60gensym4__1 = (NI)(s_p0Len_0 - paddingX60gensym4__1);
		inputIndexX60gensym4__1 = ((NI)0);
		outputIndexX60gensym4__1 = ((NI)0);
		nX60gensym4__1 = (NU32)0;
		bX60gensym4__1 = (NU32)0;
		{
			while (1) {
				if (!!((inputIndexX60gensym4__1 == inputEndsX60gensym4__1))) goto LA6;
				bX60gensym4__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym4__1]))));
				nX60gensym4__1 = (NU32)((NU64)(bX60gensym4__1) << (NU64)(((NI)16) & (32 - 1)));
				inputIndexX60gensym4__1 += ((NI)1);
				bX60gensym4__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym4__1]))));
				nX60gensym4__1 = (NU32)(nX60gensym4__1 | (NU32)((NU64)(bX60gensym4__1) << (NU64)(((NI)8) & (32 - 1))));
				inputIndexX60gensym4__1 += ((NI)1);
				bX60gensym4__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym4__1]))));
				nX60gensym4__1 = (NU32)(nX60gensym4__1 | (NU32)((NU64)(bX60gensym4__1) << (NU64)(((NI)0) & (32 - 1))));
				inputIndexX60gensym4__1 += ((NI)1);
				nimPrepareStrMutationV2((&result));
				result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
				outputIndexX60gensym4__1 += ((NI)1);
				nimPrepareStrMutationV2((&result));
				result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
				outputIndexX60gensym4__1 += ((NI)1);
				nimPrepareStrMutationV2((&result));
				result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)))- 0];
				outputIndexX60gensym4__1 += ((NI)1);
				nimPrepareStrMutationV2((&result));
				result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63)))- 0];
				outputIndexX60gensym4__1 += ((NI)1);
			} LA6: ;
		}
		{
			if (!(paddingX60gensym4__1 == ((NI)1))) goto LA9_;
			bX60gensym4__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym4__1]))));
			nX60gensym4__1 = (NU32)((NU64)(bX60gensym4__1) << (NU64)(((NI)16) & (32 - 1)));
			inputIndexX60gensym4__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
			outputIndexX60gensym4__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
			outputIndexX60gensym4__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym4__1] = 61;
			outputIndexX60gensym4__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym4__1] = 61;
			outputIndexX60gensym4__1 += ((NI)1);
		}
		goto LA7_;
LA9_: ;
		{
			if (!(paddingX60gensym4__1 == ((NI)2))) goto LA12_;
			bX60gensym4__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym4__1]))));
			nX60gensym4__1 = (NU32)((NU64)(bX60gensym4__1) << (NU64)(((NI)16) & (32 - 1)));
			inputIndexX60gensym4__1 += ((NI)1);
			bX60gensym4__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym4__1]))));
			nX60gensym4__1 = (NU32)(nX60gensym4__1 | (NU32)((NU64)(bX60gensym4__1) << (NU64)(((NI)8) & (32 - 1))));
			inputIndexX60gensym4__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
			outputIndexX60gensym4__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
			outputIndexX60gensym4__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)))- 0];
			outputIndexX60gensym4__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym4__1] = 61;
			outputIndexX60gensym4__1 += ((NI)1);
		}
		goto LA7_;
LA12_: ;
LA7_: ;
		setLengthStrV2((&result), (outputIndexX60gensym4__1));
	}
	goto LA1_;
LA3_: ;
	{
		NI paddingX60gensym37__1;
		NI inputEndsX60gensym37__1;
		NI inputIndexX60gensym37__1;
		NI outputIndexX60gensym37__1;
		NU32 nX60gensym37__1;
		NU32 bX60gensym37__1;
		setLengthStrV2((&result), ((NI)((NI)((NI)(s_p0Len_0 / ((NI)3)) + s_p0Len_0) + ((NI)6))));
		paddingX60gensym37__1 = (NI)(s_p0Len_0 % ((NI)3));
		inputEndsX60gensym37__1 = (NI)(s_p0Len_0 - paddingX60gensym37__1);
		inputIndexX60gensym37__1 = ((NI)0);
		outputIndexX60gensym37__1 = ((NI)0);
		nX60gensym37__1 = (NU32)0;
		bX60gensym37__1 = (NU32)0;
		{
			while (1) {
				if (!!((inputIndexX60gensym37__1 == inputEndsX60gensym37__1))) goto LA16;
				bX60gensym37__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym37__1]))));
				nX60gensym37__1 = (NU32)((NU64)(bX60gensym37__1) << (NU64)(((NI)16) & (32 - 1)));
				inputIndexX60gensym37__1 += ((NI)1);
				bX60gensym37__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym37__1]))));
				nX60gensym37__1 = (NU32)(nX60gensym37__1 | (NU32)((NU64)(bX60gensym37__1) << (NU64)(((NI)8) & (32 - 1))));
				inputIndexX60gensym37__1 += ((NI)1);
				bX60gensym37__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym37__1]))));
				nX60gensym37__1 = (NU32)(nX60gensym37__1 | (NU32)((NU64)(bX60gensym37__1) << (NU64)(((NI)0) & (32 - 1))));
				inputIndexX60gensym37__1 += ((NI)1);
				nimPrepareStrMutationV2((&result));
				result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
				outputIndexX60gensym37__1 += ((NI)1);
				nimPrepareStrMutationV2((&result));
				result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
				outputIndexX60gensym37__1 += ((NI)1);
				nimPrepareStrMutationV2((&result));
				result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)))- 0];
				outputIndexX60gensym37__1 += ((NI)1);
				nimPrepareStrMutationV2((&result));
				result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63)))- 0];
				outputIndexX60gensym37__1 += ((NI)1);
			} LA16: ;
		}
		{
			if (!(paddingX60gensym37__1 == ((NI)1))) goto LA19_;
			bX60gensym37__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym37__1]))));
			nX60gensym37__1 = (NU32)((NU64)(bX60gensym37__1) << (NU64)(((NI)16) & (32 - 1)));
			inputIndexX60gensym37__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
			outputIndexX60gensym37__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
			outputIndexX60gensym37__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym37__1] = 61;
			outputIndexX60gensym37__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym37__1] = 61;
			outputIndexX60gensym37__1 += ((NI)1);
		}
		goto LA17_;
LA19_: ;
		{
			if (!(paddingX60gensym37__1 == ((NI)2))) goto LA22_;
			bX60gensym37__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym37__1]))));
			nX60gensym37__1 = (NU32)((NU64)(bX60gensym37__1) << (NU64)(((NI)16) & (32 - 1)));
			inputIndexX60gensym37__1 += ((NI)1);
			bX60gensym37__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym37__1]))));
			nX60gensym37__1 = (NU32)(nX60gensym37__1 | (NU32)((NU64)(bX60gensym37__1) << (NU64)(((NI)8) & (32 - 1))));
			inputIndexX60gensym37__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
			outputIndexX60gensym37__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
			outputIndexX60gensym37__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)))- 0];
			outputIndexX60gensym37__1 += ((NI)1);
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym37__1] = 61;
			outputIndexX60gensym37__1 += ((NI)1);
		}
		goto LA17_;
LA22_: ;
LA17_: ;
		setLengthStrV2((&result), (outputIndexX60gensym37__1));
	}
LA1_: ;
	return result;
}
