/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pjson.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pjson.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ;
typedef struct tySequence__GRM41LWCr2CtjM4H9cI0HgA tySequence__GRM41LWCr2CtjM4H9cI0HgA;
typedef struct tySequence__GRM41LWCr2CtjM4H9cI0HgA_Content tySequence__GRM41LWCr2CtjM4H9cI0HgA_Content;
typedef struct tySequence__FSf5TSgM22esoEIwUgB9bLA tySequence__FSf5TSgM22esoEIwUgB9bLA;
typedef struct tySequence__FSf5TSgM22esoEIwUgB9bLA_Content tySequence__FSf5TSgM22esoEIwUgB9bLA_Content;
typedef struct tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA;
typedef struct tyTuple__txgqUAmLO89czgCvgyM9a2fg tyTuple__txgqUAmLO89czgCvgyM9a2fg;
typedef struct tyObject_NimRawSeq__wDJEL24fXeLZKhpjHjDWAA tyObject_NimRawSeq__wDJEL24fXeLZKhpjHjDWAA;
typedef NU8 tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__GRM41LWCr2CtjM4H9cI0HgA {
  NI len; tySequence__GRM41LWCr2CtjM4H9cI0HgA_Content* p;
};
struct tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ {
	tySequence__GRM41LWCr2CtjM4H9cI0HgA data;
	NI counter;
	NI first;
	NI last;
};
struct tySequence__FSf5TSgM22esoEIwUgB9bLA {
  NI len; tySequence__FSf5TSgM22esoEIwUgB9bLA_Content* p;
};
struct tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	NI64 num;
} _kind_2;
	struct {
	NF fnum;
} _kind_3;
	struct {
	NIM_BOOL bval;
} _kind_4;
	struct {
	tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ fields;
} _kind_6;
	struct {
	tySequence__FSf5TSgM22esoEIwUgB9bLA elems;
} _kind_7;
};
};
struct tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA {
	NI rc;
	NI rootIdx;
};
struct tyTuple__txgqUAmLO89czgCvgyM9a2fg {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* Field3;
};
struct tyObject_NimRawSeq__wDJEL24fXeLZKhpjHjDWAA {
	NI len;
	void* p;
};
struct tySequence__GRM41LWCr2CtjM4H9cI0HgA_Content { NI cap; tyTuple__txgqUAmLO89czgCvgyM9a2fg data[SEQ_DECL_SIZE]; };
struct tySequence__FSf5TSgM22esoEIwUgB9bLA_Content { NI cap; tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable__pureZjson_u454)(NI initialSize_p0, tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ* Result);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u91)(tySequence__GRM41LWCr2CtjM4H9cI0HgA dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u254)(tySequence__FSf5TSgM22esoEIwUgB9bLA dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, unregisterCycle__system_u3168)(tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u67)(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimIncRef)(void* p_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2746)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*, newJArray__pureZjson_u503)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_u647)(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* father_p0, tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* child_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_u657)(tySequence__FSf5TSgM22esoEIwUgB9bLA* x_p0, tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* y_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*, eqdup___pureZjson_u327)(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* src_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*, percent___pureZjson_u2144)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u321)(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, toPretty__pureZjson_u4797)(NimStringV2* result_p0, tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* node_p1, NI indent_p2, NIM_BOOL ml_p3, NIM_BOOL lstArr_p4, NI currIndent_p5);
N_LIB_PRIVATE N_NIMCALL(void, indent__pureZjson_u4737)(NimStringV2* s_p0, NI i_p1);
static N_INLINE(NimStringV2, spaces__pureZstrutils_u1138)(NI n_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatChar)(NIM_CHAR c_p0, NI count_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
static N_INLINE(NI, len__pureZjson_u2552)(tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ* t_p0);
N_LIB_PRIVATE N_NIMCALL(void, nl__pureZjson_u4745)(NimStringV2* s_p0, NIM_BOOL ml_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u486)(tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ* dest_p0, tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ* src_p1);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2743)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u324)(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw** dest_p0, tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* src_p1);
N_LIB_PRIVATE N_NIMCALL(NI, newIndent__pureZjson_u4740)(NI curr_p0, NI indent_p1, NIM_BOOL ml_p2);
N_LIB_PRIVATE N_NIMCALL(void, escapeJson__pureZjson_u4769)(NimStringV2 s_p0, NimStringV2* result_p1);
N_LIB_PRIVATE N_NIMCALL(void, escapeJsonUnquoted__pureZjson_u4748)(NimStringV2 s_p0, NimStringV2* result_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHex__pureZstrutils_u2113)(NI x_p0, NI len_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u483)(tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, toUgly__pureZjson_u4779)(NimStringV2* result_p0, tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* node_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u257)(tySequence__FSf5TSgM22esoEIwUgB9bLA* dest_p0, tySequence__FSf5TSgM22esoEIwUgB9bLA src_p1);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__pureZjson_u276)(tySequence__FSf5TSgM22esoEIwUgB9bLA* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_u187)(NimStringV2* result_p0, NI64 x_p1);
static N_INLINE(void, addFloat__system_u4774)(NimStringV2* result_p0, NF x_p1);
N_LIB_PRIVATE N_NIMCALL(void, addFloatRoundtrip__system_u4779)(NimStringV2* result_p0, NF x_p1);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_3 = {0, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_4 = { 1 | NIM_STRLIT_FLAG, "{" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_5 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_4};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_6 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_7 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_6};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_8 = { 1 | NIM_STRLIT_FLAG, " " };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_9 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_8};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_10 = { 1 | NIM_STRLIT_FLAG, "," };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_11 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_10};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_12 = { 1 | NIM_STRLIT_FLAG, "\"" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_13 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_12};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_14 = { 2 | NIM_STRLIT_FLAG, "\\n" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_15 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_14};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_16 = { 2 | NIM_STRLIT_FLAG, "\\b" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_17 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_16};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_18 = { 2 | NIM_STRLIT_FLAG, "\\f" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_19 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_18};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_20 = { 2 | NIM_STRLIT_FLAG, "\\t" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_21 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_20};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_22 = { 6 | NIM_STRLIT_FLAG, "\\u000b" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_23 = {6, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_22};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_24 = { 2 | NIM_STRLIT_FLAG, "\\r" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_25 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_24};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_26 = { 2 | NIM_STRLIT_FLAG, "\\\"" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_27 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_26};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_28 = { 5 | NIM_STRLIT_FLAG, "\\u000" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_29 = {5, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_28};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_30 = { 4 | NIM_STRLIT_FLAG, "\\u00" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_31 = {4, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_30};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_32 = { 2 | NIM_STRLIT_FLAG, "\\\\" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_33 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_32};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_34 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_12};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_35 = { 2 | NIM_STRLIT_FLAG, ": " };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_36 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_35};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_37 = { 1 | NIM_STRLIT_FLAG, "}" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_38 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_37};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_39 = { 2 | NIM_STRLIT_FLAG, "{}" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_40 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_39};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_41 = { 1 | NIM_STRLIT_FLAG, "[" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_42 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_41};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_43 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_10};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_44 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_45 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_44};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_46 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_4};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_47 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_10};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_48 = { 1 | NIM_STRLIT_FLAG, ":" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_49 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_48};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_50 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_37};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_51 = { 4 | NIM_STRLIT_FLAG, "true" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_52 = {4, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_51};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_53 = { 5 | NIM_STRLIT_FLAG, "false" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_54 = {5, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_53};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_55 = { 4 | NIM_STRLIT_FLAG, "null" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_56 = {4, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_55};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_57 = {4, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_51};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_58 = {5, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_53};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_59 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_41};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_60 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_10};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_61 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_44};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_62 = { 2 | NIM_STRLIT_FLAG, "[]" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_63 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_62};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_64 = {4, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_55};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4183;
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastDyn)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA*) (T5_));
		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		{
			if (!result) goto LA13_;
			{
				if (!(((NI)0) < (*cell_1).rootIdx)) goto LA17_;
				unregisterCycle__system_u3168(cell_1);
			}
LA17_: ;
		}
LA13_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u254)(tySequence__FSf5TSgM22esoEIwUgB9bLA dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLastDyn(dest_p0.p->data[colontmp_]);
				if (!T6_) goto LA7_;
				eqdestroy___pureZjson_u67((&(*dest_p0.p->data[colontmp_])));
				nimRawDispose(dest_p0.p->data[colontmp_], ((NI)8));
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u67)(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* dest_p0) {
	switch ((*dest_p0).kind) {
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)4):
	{
		if ((*dest_p0)._kind_1.str.p && !((*dest_p0)._kind_1.str.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0)._kind_1.str.p);
}
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)2):
	{
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)3):
	{
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)1):
	{
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)0):
	{
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)5):
	{
		eqdestroy___pureZjson_u91((*dest_p0)._kind_6.fields.data);
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)6):
	{
		eqdestroy___pureZjson_u254((*dest_p0)._kind_7.elems);
	}
	break;
	default: __builtin_unreachable();
	}
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4183);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*, newJObject__pureZjson_u440)(void) {
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* result;
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*) nimNewObj(sizeof(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw), NIM_ALIGNOF(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw));
	(*T1_).kind = ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)5);
	initOrderedTable__pureZjson_u454(((NI)2), (&(*T1_)._kind_6.fields));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZjson_u330)(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw** dest_p0, tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* src_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastDyn((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___pureZjson_u67((&(*(*dest_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA4_: ;
	(*dest_p0) = src_p1;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZjson_u318)(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw** dest_p0) {
	(*dest_p0) = 0;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	NI T2_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	T2_ = (NI)0;
	T2_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
	(*((tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA*) (T1_))).rc = pluspercent___system_u793((*((tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA*) (T2_))).rc, ((NI)16));
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*, eqdup___pureZjson_u327)(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* src_p0) {
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
		nimIncRef(src_p0);
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*, percent___pureZjson_u2144)(NimStringV2 s_p0) {
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* result;
	NimStringV2 colontmpD_;
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* T1_;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*) nimNewObj(sizeof(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw), NIM_ALIGNOF(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw));
	(*T1_).kind = ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)4);
	colontmpD_ = eqdup___system_u2746(s_p0);
	(*T1_)._kind_1.str = colontmpD_;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*, percent___pureZjson_u2154)(NI n_p0) {
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* result;
	NI colontmpD_;
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* T1_;
	colontmpD_ = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*) nimNewObj(sizeof(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw), NIM_ALIGNOF(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw));
	(*T1_).kind = ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)2);
	colontmpD_ = n_p0;
	(*T1_)._kind_2.num = ((NI64) (colontmpD_));
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u321)(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastDyn(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pureZjson_u67((&(*dest_p0)));
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*, newJArray__pureZjson_u503)(void) {
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* result;
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* T1_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*) nimNewObj(sizeof(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw), NIM_ALIGNOF(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw));
	(*T1_).kind = ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)6);
	(*T1_)._kind_7.elems.len = 0; (*T1_)._kind_7.elems.p = (tySequence__FSf5TSgM22esoEIwUgB9bLA_Content*) newSeqPayload(0, sizeof(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*), NIM_ALIGNOF(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*));
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_u647)(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* father_p0, tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* child_p1) {
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_ = NIM_NIL;
	colontmpD_ = eqdup___pureZjson_u327(child_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	add__pureZjson_u657((&(*father_p0)._kind_7.elems), colontmpD_);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*, percent___nymph_u3261)(NimStringV2* elements_p0, NI elements_p0Len_0) {
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = newJArray__pureZjson_u503();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NimStringV2* elem_1;
		NI i_1;
		elem_1 = (NimStringV2*)0;
		i_1 = ((NI)0);
		{
			while (1) {
				tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* colontmpD_;
				if (!(i_1 < elements_p0Len_0)) goto LA3;
				colontmpD_ = NIM_NIL;
				elem_1 = (&elements_p0[i_1]);
				colontmpD_ = percent___pureZjson_u2144((*elem_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				add__pureZjson_u647(result, colontmpD_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				i_1 += ((NI)1);
				eqdestroy___pureZjson_u321(colontmpD_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*, percent___pureZjson_u2170)(NIM_BOOL b_p0) {
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* result;
	NIM_BOOL colontmpD_;
	tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* T1_;
	colontmpD_ = (NIM_BOOL)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw*) nimNewObj(sizeof(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw), NIM_ALIGNOF(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw));
	(*T1_).kind = ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)1);
	colontmpD_ = b_p0;
	(*T1_)._kind_4.bval = colontmpD_;
	result = T1_;
	return result;
}
static N_INLINE(NimStringV2, spaces__pureZstrutils_u1138)(NI n_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = nsuRepeatChar(32, n_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, indent__pureZjson_u4737)(NimStringV2* s_p0, NI i_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD_ = spaces__pureZstrutils_u1138((i_p1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*s_p0)), colontmpD_.len + 0);
appendString((&(*s_p0)), colontmpD_);
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
}
static N_INLINE(NI, len__pureZjson_u2552)(tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ* t_p0) {
	NI result;
	result = (*t_p0).counter;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nl__pureZjson_u4745)(NimStringV2* s_p0, NIM_BOOL ml_p1) {
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		if (!ml_p1) goto LA4_;
		T1_ = TM__9b9bytt1stv9cZ8uqII7HFgew_7;
	}
	goto LA2_;
LA4_: ;
	{
		T1_ = TM__9b9bytt1stv9cZ8uqII7HFgew_9;
	}
LA2_: ;
	prepareAdd((&(*s_p0)), T1_.len + 0);
appendString((&(*s_p0)), T1_);
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0) {
	NIM_BOOL result;
	result = !((hcode_p0 == ((NI)0)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u324)(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw** dest_p0, tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* src_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!src_p1) goto LA3_;
		nimIncRef(src_p1);
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLastDyn((*dest_p0));
		if (!T7_) goto LA8_;
		eqdestroy___pureZjson_u67((&(*(*dest_p0))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA8_: ;
	(*dest_p0) = src_p1;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, newIndent__pureZjson_u4740)(NI curr_p0, NI indent_p1, NIM_BOOL ml_p2) {
	NI result;
{	{
		if (!ml_p2) goto LA3_;
		result = (NI)(curr_p0 + indent_p1);
		goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		result = indent_p1;
		goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, escapeJsonUnquoted__pureZjson_u4748)(NimStringV2 s_p0, NimStringV2* result_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_CHAR c_1;
		NI i_1;
		NI L_1;
		c_1 = (NIM_CHAR)0;
		i_1 = ((NI)0);
		L_1 = s_p0.len;
		{
			while (1) {
				if (!(i_1 < L_1)) goto LA3;
				c_1 = s_p0.p->data[i_1];
				switch (((NU8)(c_1))) {
				case 10:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_15);
				}
				break;
				case 8:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_17);
				}
				break;
				case 12:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_19);
				}
				break;
				case 9:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_21);
				}
				break;
				case 11:
				{
					prepareAdd((&(*result_p1)), 6);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_23);
				}
				break;
				case 13:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_25);
				}
				break;
				case 34:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_27);
				}
				break;
				case 0 ... 7:
				{
					NimStringV2 colontmpD_;
					NimStringV2 colontmpD__2;
					NimStringV2 T12_;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
					T12_.len = 0; T12_.p = NIM_NIL;
					colontmpD_ = dollar___systemZdollars_u14(((NU8)(c_1)));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					T12_ = rawNewString(colontmpD_.len + 5);
appendString((&T12_), TM__9b9bytt1stv9cZ8uqII7HFgew_29);
appendString((&T12_), colontmpD_);
					colontmpD__2 = T12_;
					prepareAdd((&(*result_p1)), colontmpD__2.len + 0);
appendString((&(*result_p1)), colontmpD__2);
					if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				}
				break;
				case 14 ... 31:
				{
					NimStringV2 colontmpD__3;
					NimStringV2 colontmpD__4;
					NimStringV2 T14_;
					colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
					colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
					T14_.len = 0; T14_.p = NIM_NIL;
					colontmpD__3 = toHex__pureZstrutils_u2113(((NU8)(c_1)), ((NI)2));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					T14_ = rawNewString(colontmpD__3.len + 4);
appendString((&T14_), TM__9b9bytt1stv9cZ8uqII7HFgew_31);
appendString((&T14_), colontmpD__3);
					colontmpD__4 = T14_;
					prepareAdd((&(*result_p1)), colontmpD__4.len + 0);
appendString((&(*result_p1)), colontmpD__4);
					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
					if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
				}
				break;
				case 92:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_33);
				}
				break;
				default:
				{
					nimAddCharV1((&(*result_p1)), c_1);
				}
				break;
				}
				i_1 += ((NI)1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, escapeJson__pureZjson_u4769)(NimStringV2 s_p0, NimStringV2* result_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	prepareAdd((&(*result_p1)), 1);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_13);
	escapeJsonUnquoted__pureZjson_u4748(s_p0, result_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*result_p1)), 1);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_34);
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__wDJEL24fXeLZKhpjHjDWAA*) (x_p0))).p == (*((tyObject_NimRawSeq__wDJEL24fXeLZKhpjHjDWAA*) (y_p1))).p);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u257)(tySequence__FSf5TSgM22esoEIwUgB9bLA* dest_p0, tySequence__FSf5TSgM22esoEIwUgB9bLA src_p1) {
	NI T6_;
	NI colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__pureZjson_u276((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			{
				if (!src_p1.p->data[colontmp_]) goto LA12_;
				nimIncRef(src_p1.p->data[colontmp_]);
			}
LA12_: ;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = nimDecRefIsLastDyn((*dest_p0).p->data[colontmp_]);
				if (!T16_) goto LA17_;
				eqdestroy___pureZjson_u67((&(*(*dest_p0).p->data[colontmp_])));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimRawDispose((*dest_p0).p->data[colontmp_], ((NI)8));
			}
LA17_: ;
			(*dest_p0).p->data[colontmp_] = src_p1.p->data[colontmp_];
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
static N_INLINE(void, addFloat__system_u4774)(NimStringV2* result_p0, NF x_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	addFloatRoundtrip__system_u4779(result_p0, x_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, toUgly__pureZjson_u4779)(NimStringV2* result_p0, tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* node_p1) {
	NIM_BOOL comma_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	comma_1 = NIM_FALSE;
	switch ((*node_p1).kind) {
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)6):
	{
		prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_42);
		{
			tySequence__FSf5TSgM22esoEIwUgB9bLA colontmp_;
			tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw** child_1;
			NI i_1;
			NI L_1;
			NI T3_;
			colontmp_.len = 0; colontmp_.p = NIM_NIL;
			child_1 = (tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw**)0;
			eqcopy___pureZjson_u257((&colontmp_), (*node_p1)._kind_7.elems);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			i_1 = ((NI)0);
			T3_ = colontmp_.len;
			L_1 = T3_;
			{
				while (1) {
					if (!(i_1 < L_1)) goto LA5;
					child_1 = &colontmp_.p->data[i_1];
					{
						if (!comma_1) goto LA8_;
						prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_43);
					}
					goto LA6_;
LA8_: ;
					{
						comma_1 = NIM_TRUE;
					}
LA6_: ;
					toUgly__pureZjson_u4779(result_p0, (*child_1));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					i_1 += ((NI)1);
				} LA5: ;
			}
			eqdestroy___pureZjson_u254(colontmp_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_45);
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)5):
	{
		prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_46);
		{
			NimStringV2 key_1;
			tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* value_1;
			tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ colontmp__2;
			NI L_2;
			key_1.len = 0; key_1.p = NIM_NIL;
			value_1 = NIM_NIL;
			nimZeroMem((void*)(&colontmp__2), sizeof(tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ));
			eqcopy___pureZjson_u486((&colontmp__2), (&(*node_p1)._kind_6.fields));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			L_2 = len__pureZjson_u2552((&colontmp__2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			{
				NI h_1;
				if (!(((NI)0) < colontmp__2.counter)) goto LA15_;
				h_1 = colontmp__2.first;
				{
					while (1) {
						NI nxt_1;
						if (!(((NI)0) <= h_1)) goto LA18;
						nxt_1 = colontmp__2.data.p->data[h_1].Field1;
						{
							NIM_BOOL T21_;
							T21_ = (NIM_BOOL)0;
							T21_ = isFilled__pureZcollectionsZtables_u31(colontmp__2.data.p->data[h_1].Field0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T21_) goto LA22_;
							eqcopy___system_u2743((&key_1), colontmp__2.data.p->data[h_1].Field2);
							eqcopy___pureZjson_u324(&value_1, colontmp__2.data.p->data[h_1].Field3);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							{
								if (!comma_1) goto LA26_;
								prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_47);
							}
							goto LA24_;
LA26_: ;
							{
								comma_1 = NIM_TRUE;
							}
LA24_: ;
							escapeJson__pureZjson_u4769(key_1, result_p0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_49);
							toUgly__pureZjson_u4779(result_p0, value_1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
LA22_: ;
						h_1 = nxt_1;
					} LA18: ;
				}
			}
LA15_: ;
			eqdestroy___pureZjson_u483((&colontmp__2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			eqdestroy___pureZjson_u321(value_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (key_1.p && !(key_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(key_1.p);
}
		}
		prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_50);
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)4):
	{
		{
			if (!(*node_p1).isUnquoted) goto LA32_;
			prepareAdd((&(*result_p0)), (*node_p1)._kind_1.str.len + 0);
appendString((&(*result_p0)), (*node_p1)._kind_1.str);
		}
		goto LA30_;
LA32_: ;
		{
			escapeJson__pureZjson_u4769((*node_p1)._kind_1.str, result_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA30_: ;
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)2):
	{
		addInt__stdZprivateZdigitsutils_u187(result_p0, (*node_p1)._kind_2.num);
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)3):
	{
		addFloat__system_u4774(result_p0, (*node_p1)._kind_3.fnum);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)1):
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		NimStringV2 T38_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		T38_.len = 0; T38_.p = NIM_NIL;
		{
			if (!(*node_p1)._kind_4.bval) goto LA41_;
			colontmpD_ = TM__9b9bytt1stv9cZ8uqII7HFgew_52;
			T38_ = colontmpD_;
		}
		goto LA39_;
LA41_: ;
		{
			colontmpD__2 = TM__9b9bytt1stv9cZ8uqII7HFgew_54;
			T38_ = colontmpD__2;
		}
LA39_: ;
		prepareAdd((&(*result_p0)), T38_.len + 0);
appendString((&(*result_p0)), T38_);
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)0):
	{
		prepareAdd((&(*result_p0)), 4);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_56);
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, toPretty__pureZjson_u4797)(NimStringV2* result_p0, tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* node_p1, NI indent_p2, NIM_BOOL ml_p3, NIM_BOOL lstArr_p4, NI currIndent_p5) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	switch ((*node_p1).kind) {
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)5):
	{
		{
			if (!lstArr_p4) goto LA4_;
			indent__pureZjson_u4737(result_p0, currIndent_p5);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA4_: ;
		{
			NI T8_;
			NI i_1;
			T8_ = (NI)0;
			T8_ = len__pureZjson_u2552((&(*node_p1)._kind_6.fields));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!(((NI)0) < T8_)) goto LA9_;
			prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_5);
			nl__pureZjson_u4745(result_p0, ml_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			i_1 = ((NI)0);
			{
				NimStringV2 key_1;
				tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* val_1;
				tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ colontmp_;
				NI L_1;
				key_1.len = 0; key_1.p = NIM_NIL;
				val_1 = NIM_NIL;
				nimZeroMem((void*)(&colontmp_), sizeof(tyObject_OrderedTable__X9aB9aZookFlnDw5Sc80bOpQ));
				eqcopy___pureZjson_u486((&colontmp_), (&(*node_p1)._kind_6.fields));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				L_1 = len__pureZjson_u2552((&colontmp_));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				{
					NI h_1;
					if (!(((NI)0) < colontmp_.counter)) goto LA14_;
					h_1 = colontmp_.first;
					{
						while (1) {
							NI nxt_1;
							if (!(((NI)0) <= h_1)) goto LA17;
							nxt_1 = colontmp_.data.p->data[h_1].Field1;
							{
								NIM_BOOL T20_;
								NI T27_;
								NI T28_;
								T20_ = (NIM_BOOL)0;
								T20_ = isFilled__pureZcollectionsZtables_u31(colontmp_.data.p->data[h_1].Field0);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								if (!T20_) goto LA21_;
								eqcopy___system_u2743((&key_1), colontmp_.data.p->data[h_1].Field2);
								eqcopy___pureZjson_u324(&val_1, colontmp_.data.p->data[h_1].Field3);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								{
									if (!(((NI)0) < i_1)) goto LA25_;
									prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_11);
									nl__pureZjson_u4745(result_p0, ml_p3);
									if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								}
LA25_: ;
								i_1 += ((NI)1);
								T27_ = (NI)0;
								T27_ = newIndent__pureZjson_u4740(currIndent_p5, indent_p2, ml_p3);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								indent__pureZjson_u4737(result_p0, T27_);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								escapeJson__pureZjson_u4769(key_1, result_p0);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								prepareAdd((&(*result_p0)), 2);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_36);
								T28_ = (NI)0;
								T28_ = newIndent__pureZjson_u4740(currIndent_p5, indent_p2, ml_p3);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								toPretty__pureZjson_u4797(result_p0, val_1, indent_p2, ml_p3, NIM_FALSE, T28_);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							}
LA21_: ;
							h_1 = nxt_1;
						} LA17: ;
					}
				}
LA14_: ;
				eqdestroy___pureZjson_u483((&colontmp_));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				eqdestroy___pureZjson_u321(val_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (key_1.p && !(key_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(key_1.p);
}
			}
			nl__pureZjson_u4745(result_p0, ml_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			indent__pureZjson_u4737(result_p0, currIndent_p5);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_38);
		}
		goto LA6_;
LA9_: ;
		{
			prepareAdd((&(*result_p0)), 2);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_40);
		}
LA6_: ;
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)4):
	{
		{
			if (!lstArr_p4) goto LA33_;
			indent__pureZjson_u4737(result_p0, currIndent_p5);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA33_: ;
		toUgly__pureZjson_u4779(result_p0, node_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)2):
	{
		{
			if (!lstArr_p4) goto LA38_;
			indent__pureZjson_u4737(result_p0, currIndent_p5);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA38_: ;
		addInt__stdZprivateZdigitsutils_u187(result_p0, (*node_p1)._kind_2.num);
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)3):
	{
		{
			if (!lstArr_p4) goto LA43_;
			indent__pureZjson_u4737(result_p0, currIndent_p5);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA43_: ;
		addFloat__system_u4774(result_p0, (*node_p1)._kind_3.fnum);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)1):
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		NimStringV2 T50_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		{
			if (!lstArr_p4) goto LA48_;
			indent__pureZjson_u4737(result_p0, currIndent_p5);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA48_: ;
		T50_.len = 0; T50_.p = NIM_NIL;
		{
			if (!(*node_p1)._kind_4.bval) goto LA53_;
			colontmpD_ = TM__9b9bytt1stv9cZ8uqII7HFgew_57;
			T50_ = colontmpD_;
		}
		goto LA51_;
LA53_: ;
		{
			colontmpD__2 = TM__9b9bytt1stv9cZ8uqII7HFgew_58;
			T50_ = colontmpD__2;
		}
LA51_: ;
		prepareAdd((&(*result_p0)), T50_.len + 0);
appendString((&(*result_p0)), T50_);
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)6):
	{
		{
			if (!lstArr_p4) goto LA59_;
			indent__pureZjson_u4737(result_p0, currIndent_p5);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA59_: ;
		{
			NI T63_;
			T63_ = (*node_p1)._kind_7.elems.len;
			if (!!((T63_ == ((NI)0)))) goto LA64_;
			prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_59);
			nl__pureZjson_u4745(result_p0, ml_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			{
				NI i_2;
				NI colontmp__2;
				NI T67_;
				NI res_1;
				i_2 = (NI)0;
				colontmp__2 = (NI)0;
				T67_ = (*node_p1)._kind_7.elems.len;
				colontmp__2 = (NI)(T67_ - ((NI)1));
				res_1 = ((NI)0);
				{
					while (1) {
						NI T74_;
						if (!(res_1 <= colontmp__2)) goto LA69;
						i_2 = ((NI) (res_1));
						{
							if (!(((NI)0) < i_2)) goto LA72_;
							prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_60);
							nl__pureZjson_u4745(result_p0, ml_p3);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
LA72_: ;
						T74_ = (NI)0;
						T74_ = newIndent__pureZjson_u4740(currIndent_p5, indent_p2, ml_p3);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						toPretty__pureZjson_u4797(result_p0, (*node_p1)._kind_7.elems.p->data[i_2], indent_p2, ml_p3, NIM_TRUE, T74_);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						res_1 += ((NI)1);
					} LA69: ;
				}
			}
			nl__pureZjson_u4745(result_p0, ml_p3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			indent__pureZjson_u4737(result_p0, currIndent_p5);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_61);
		}
		goto LA61_;
LA64_: ;
		{
			prepareAdd((&(*result_p0)), 2);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_63);
		}
LA61_: ;
	}
	break;
	case ((tyEnum_JsonNodeKind__ZtUNte4eWKeL9b1q12LWvrw)0):
	{
		{
			if (!lstArr_p4) goto LA79_;
			indent__pureZjson_u4737(result_p0, currIndent_p5);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA79_: ;
		prepareAdd((&(*result_p0)), 4);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_64);
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, pretty__pureZjson_u4875)(tyObject_JsonNodeObj__QwWxs1vx7GHCYui2hS09aiw* node_p0, NI indent_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = TM__9b9bytt1stv9cZ8uqII7HFgew_3;
	toPretty__pureZjson_u4797((&result), node_p0, indent_p1, NIM_TRUE, NIM_FALSE, ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
