/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pos.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pos.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <unistd.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg tyTuple__7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg tySequence__TM0VfWZgOhRIJ9bpQyFJFrg;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content;
typedef struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg {
	NimStringV2 Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg {
  NI len; tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__TM0VfWZgOhRIJ9bpQyFJFrg trace;
	Exception* up;
};
struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content { NI cap; tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, nossplitFile)(NimStringV2 path_p0, tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetAppFilename)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getApplAux__pureZos_u182)(NimStringV2 procPath_p0);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2749)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getApplHeuristic__pureZos_u186)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, paramStr__stdZcmdline_u55)(NI i_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9036)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2740)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3702)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZos_u197)(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* dest_p0);
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_2 = { 14 | NIM_STRLIT_FLAG, "/proc/self/exe" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_3 = {14, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_2};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_4 = { 4 | NIM_STRLIT_FLAG, "PATH" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_5 = {4, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_4};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_6 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_7 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_6};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_8 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_6};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4183;
extern NIM_THREADVAR Exception* currException__system_u3669;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getApplAux__pureZos_u182)(NimStringV2 procPath_p0) {
	NimStringV2 result;
	NI len_1;
	result = mnewString(((NI)1024));
	len_1 = readlink(nimToCStringConv(procPath_p0), nimToCStringConv(result), ((NI)1024));
	{
		NimStringV2 T5_;
		if (!(((NI)1024) < len_1)) goto LA3_;
		T5_.len = 0; T5_.p = NIM_NIL;
		T5_ = mnewString(((NI)(len_1 + ((NI)1))));
		eqsink___system_u2749((&result), T5_);
		len_1 = readlink(nimToCStringConv(procPath_p0), nimToCStringConv(result), len_1);
	}
LA3_: ;
	{
		if (!(len_1 < ((NI)0))) goto LA8_;
		len_1 = ((NI)0);
	}
LA8_: ;
	setLengthStrV2((&result), (len_1));
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4183);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getApplHeuristic__pureZos_u186)(void) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = paramStr__stdZcmdline_u55(((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) < result.len);
		if (!(T3_)) goto LA4_;
		T3_ = !(((NU8)(result.p->data[((NI)0)]) == (NU8)(47)));
LA4_: ;
		if (!T3_) goto LA5_;
		{
			NimStringV2 p_1;
			NimStringV2 colontmp_;
			NI lastX60gensym37__1;
			NI splitsX60gensym37__1;
			p_1.len = 0; p_1.p = NIM_NIL;
			colontmp_.len = 0; colontmp_.p = NIM_NIL;
			colontmp_ = getEnv__stdZenvvars_u15(TM__yu6cxgKBBXbNsTkT9cyMd4g_5, TM__yu6cxgKBBXbNsTkT9cyMd4g_7);
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			lastX60gensym37__1 = ((NI)0);
			splitsX60gensym37__1 = ((NI)-1);
			{
				while (1) {
					NimStringV2 x_1;
					NI firstX60gensym37__1;
					NimStringV2 T20_;
					if (!(lastX60gensym37__1 <= colontmp_.len)) goto LA10;
					x_1.len = 0; x_1.p = NIM_NIL;
					firstX60gensym37__1 = lastX60gensym37__1;
					{
						while (1) {
							NIM_BOOL T14_;
							T14_ = (NIM_BOOL)0;
							T14_ = (lastX60gensym37__1 < colontmp_.len);
							if (!(T14_)) goto LA15_;
							T14_ = !((((NU8)(colontmp_.p->data[lastX60gensym37__1])) == ((NU8)(58))));
LA15_: ;
							if (!T14_) goto LA13;
							lastX60gensym37__1 += ((NI)1);
						} LA13: ;
					}
					{
						if (!(splitsX60gensym37__1 == ((NI)0))) goto LA18_;
						lastX60gensym37__1 = colontmp_.len;
					}
LA18_: ;
					T20_.len = 0; T20_.p = NIM_NIL;
					T20_ = substr__system_u9036(colontmp_, firstX60gensym37__1, (NI)(lastX60gensym37__1 - ((NI)1)));
					eqsink___system_u2749((&p_1), T20_);
					x_1 = nosjoinPath(p_1, result);
					if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
					{
						NIM_BOOL T23_;
						T23_ = (NIM_BOOL)0;
						T23_ = nosfileExists(x_1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
						if (!T23_) goto LA24_;
						result = x_1;
						eqwasMoved___system_u2740((&x_1));
						if (x_1.p && !(x_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(x_1.p);
}
						if (colontmp_.p && !(colontmp_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp_.p);
}
						if (p_1.p && !(p_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(p_1.p);
}
						goto BeforeRet_;
					}
LA24_: ;
					{
						if (!(splitsX60gensym37__1 == ((NI)0))) goto LA28_;
						if (x_1.p && !(x_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(x_1.p);
}
						goto LA9;
					}
LA28_: ;
					splitsX60gensym37__1 -= ((NI)1);
					lastX60gensym37__1 += ((NI)1);
					{
						LA11_:;
					}
					{
						if (x_1.p && !(x_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(x_1.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				} LA10: ;
			} LA9: ;
			{
				LA8_:;
			}
			{
				if (colontmp_.p && !(colontmp_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp_.p);
}
				if (p_1.p && !(p_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(p_1.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
	}
LA5_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = currException__system_u3669;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3702(&currException__system_u3669, (*currException__system_u3669).up, NIM_FALSE);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetAppFilename)(void) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = getApplAux__pureZos_u182(TM__yu6cxgKBBXbNsTkT9cyMd4g_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NimStringV2 T6_;
		NimStringV2 T7_;
		if (!(result.len == ((NI)0))) goto LA3_;
		T6_.len = 0; T6_.p = NIM_NIL;
		T7_.len = 0; T7_.p = NIM_NIL;
		T7_ = getApplHeuristic__pureZos_u186();
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T7_); goto LA5_;}
		eqsink___system_u2749((&result), T7_);
		if (NIM_UNLIKELY(*nimErr_)) {
			LA5_:;
			if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 675043584)) {
				*nimErr_ = NIM_FALSE;
				eqsink___system_u2749((&result), TM__yu6cxgKBBXbNsTkT9cyMd4g_8);
				popCurrentException();
				LA9_:;
			}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetAppDir)(void) {
	NimStringV2 result;
	tyTuple__7q7q3E6Oj24ZNVJb9aonhAg colontmpD_;
	NimStringV2 colontmpD__2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__2 = nosgetAppFilename();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nossplitFile(colontmpD__2, (&colontmpD_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = colontmpD_.Field0;
	eqwasMoved___system_u2740((&colontmpD_.Field0));
	if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	eqdestroy___pureZos_u197((&colontmpD_));
	}BeforeRet_: ;
	return result;
}
