/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pstd@scmdline.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pstd@scmdline.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw;
typedef struct tyObject_Defect__EL9aN6agFLgcb8D9bbKrC9cFA tyObject_Defect__EL9aN6agFLgcb8D9bbKrC9cFA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg tySequence__TM0VfWZgOhRIJ9bpQyFJFrg;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content;
typedef struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg {
  NI len; tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__TM0VfWZgOhRIJ9bpQyFJFrg trace;
	Exception* up;
};
struct tyObject_Defect__EL9aN6agFLgcb8D9bbKrC9cFA {
	Exception Sup;
};
struct tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw {
	tyObject_Defect__EL9aN6agFLgcb8D9bbKrC9cFA Sup;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content { NI cap; tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(NI, paramCount__stdZcmdline_u61)(void);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, paramStr__stdZcmdline_u55)(NI i_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2740)(NimStringV2* dest_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u29)(NI32 xX60gensym3__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
extern TNimTypeV2 NTIv2__VGLiEs425pQTea1LYjRwHw_;
static const struct {
  NI cap; NIM_CHAR data[43+1];
} TM__MZPGKsURfItHSi3RvnOT8Q_2 = { 43 | NIM_STRLIT_FLAG, "index out of bounds, the container is empty" };
static const NimStringV2 TM__MZPGKsURfItHSi3RvnOT8Q_3 = {43, (NimStrPayload*)&TM__MZPGKsURfItHSi3RvnOT8Q_2};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__MZPGKsURfItHSi3RvnOT8Q_4 = { 6 | NIM_STRLIT_FLAG, "index " };
static const NimStringV2 TM__MZPGKsURfItHSi3RvnOT8Q_5 = {6, (NimStrPayload*)&TM__MZPGKsURfItHSi3RvnOT8Q_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__MZPGKsURfItHSi3RvnOT8Q_6 = { 13 | NIM_STRLIT_FLAG, " not in 0 .. " };
static const NimStringV2 TM__MZPGKsURfItHSi3RvnOT8Q_7 = {13, (NimStrPayload*)&TM__MZPGKsURfItHSi3RvnOT8Q_6};
extern int cmdCount;
extern NCSTRING* cmdLine;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4183;
N_LIB_PRIVATE N_NIMCALL(NI, paramCount__stdZcmdline_u61)(void) {
	NI result;
	result = ((NI) ((NI32)(cmdCount - ((NI32)1))));
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4183);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, paramStr__stdZcmdline_u55)(NI i_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (i_p0 < ((NI) (cmdCount)));
		if (!(T3_)) goto LA4_;
		T3_ = (((NI)0) <= i_p0);
LA4_: ;
		if (!T3_) goto LA5_;
		result = cstrToNimstr(cmdLine[i_p0]);
	}
	goto LA1_;
LA5_: ;
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw* T9_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		T9_ = NIM_NIL;
		T9_ = (tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw*) nimNewObj(sizeof(tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw), NIM_ALIGNOF(tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw));
		(*T9_).Sup.Sup.Sup.m_type = (&NTIv2__VGLiEs425pQTea1LYjRwHw_);
		(*T9_).Sup.Sup.name = "IndexDefect";
		{
			NimStringV2 blitTmp_1;
			if (!((NI32)(cmdCount - ((NI32)1)) < ((NI32)0))) goto LA12_;
			colontmpD_ = TM__MZPGKsURfItHSi3RvnOT8Q_3;
			blitTmp_1 = colontmpD_;
			eqwasMoved___system_u2740((&colontmpD_));
			(*T9_).Sup.Sup.message = blitTmp_1;
		}
		goto LA10_;
LA12_: ;
		{
			NimStringV2 colontmpD__3;
			NimStringV2 colontmpD__4;
			NimStringV2 T15_;
			NimStringV2 blitTmp_2;
			colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
			colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
			T15_.len = 0; T15_.p = NIM_NIL;
			colontmpD__3 = dollar___systemZdollars_u14(i_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			colontmpD__4 = dollar___systemZdollars_u29((NI32)(cmdCount - ((NI32)1)));
			if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			T15_ = rawNewString(colontmpD__3.len + colontmpD__4.len + 19);
appendString((&T15_), TM__MZPGKsURfItHSi3RvnOT8Q_5);
appendString((&T15_), colontmpD__3);
appendString((&T15_), TM__MZPGKsURfItHSi3RvnOT8Q_7);
appendString((&T15_), colontmpD__4);
			colontmpD__2 = T15_;
			if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
			blitTmp_2 = colontmpD__2;
			eqwasMoved___system_u2740((&colontmpD__2));
			(*T9_).Sup.Sup.message = blitTmp_2;
		}
LA10_: ;
		(*T9_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T9_, "IndexDefect", "paramStr", "cmdline.nim", 272);
goto LA8_;
		{
			LA8_:;
		}
		{
			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, commandLineParams__stdZcmdline_u63)(void) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NI i_1;
		NI colontmp_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = paramCount__stdZcmdline_u61();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		res_1 = ((NI)1);
		{
			while (1) {
				NimStringV2 T4_;
				if (!(res_1 <= colontmp_)) goto LA3;
				i_1 = ((NI) (res_1));
				T4_.len = 0; T4_.p = NIM_NIL;
				T4_ = paramStr__stdZcmdline_u55(i_1);
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T4_); goto BeforeRet_;}
				add__stdZenumutils_u70((&result), T4_);
				res_1 += ((NI)1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
