/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pstd@ssysrand.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pstd@ssysrand.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <unistd.h>
#include <sys/syscall.h>
#include <sys/syscall.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef int tyArray__Zwjt9bECqO23Zah8rGoMkoQ[2];
static N_INLINE(NI, urandomInternalImpl__stdZsysrand_u18)(NU8* dest_p0, NI dest_p0Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u28)(NimStringV2 msg_p0);
static N_INLINE(NIM_BOOL, contains__stdZsysrand_u35)(int* a_p0, NI a_p0Len_0, int item_p1);
static N_INLINE(NI, find__stdZsysrand_u40)(int* a_p0, NI a_p0Len_0, int item_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u122)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__sT0fWggTrXhnxQ79bl9a8nHg_2 = { 11 | NIM_STRLIT_FLAG, "unreachable" };
static const NimStringV2 TM__sT0fWggTrXhnxQ79bl9a8nHg_3 = {11, (NimStrPayload*)&TM__sT0fWggTrXhnxQ79bl9a8nHg_2};
static NIM_CONST tyArray__Zwjt9bECqO23Zah8rGoMkoQ TM__sT0fWggTrXhnxQ79bl9a8nHg_4 = {((int)4),
((int)11)}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4183;
static N_INLINE(NI, find__stdZsysrand_u40)(int* a_p0, NI a_p0Len_0, int item_p1) {
	NI result;
{	result = ((NI)0);
	{
		int* i_1;
		NI i_2;
		i_1 = (int*)0;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < a_p0Len_0)) goto LA3;
				i_1 = (&a_p0[i_2]);
				{
					if (!((*i_1) == item_p1)) goto LA6_;
					goto BeforeRet_;
				}
LA6_: ;
				result += ((NI)1);
				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	result = ((NI)-1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, contains__stdZsysrand_u35)(int* a_p0, NI a_p0Len_0, int item_p1) {
	NIM_BOOL result;
	NI T1_;
{	T1_ = (NI)0;
	T1_ = find__stdZsysrand_u40(a_p0, a_p0Len_0, item_p1);
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4183);
	return result;
}
static N_INLINE(NI, urandomInternalImpl__stdZsysrand_u18)(NU8* dest_p0, NI dest_p0Len_0) {
	NI result;
	NI sizeX60gensym1__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = ((NI)0);
	sizeX60gensym1__1 = dest_p0Len_0;
	{
		if (!(sizeX60gensym1__1 == ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	{
		while (1) {
			NI readBytesX60gensym1__1;
			long T7_;
			if (!(result < sizeX60gensym1__1)) goto LA6;
			T7_ = (long)0;
			T7_ = syscall(SYS_getrandom, (&dest_p0[result]), ((int) ((NI)(sizeX60gensym1__1 - result))), ((NI)0));
			readBytesX60gensym1__1 = ((NI) (T7_));
			{
				if (!(readBytesX60gensym1__1 == ((NI)0))) goto LA10_;
				raiseAssert__stdZassertions_u28(TM__sT0fWggTrXhnxQ79bl9a8nHg_3);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
			goto LA8_;
LA10_: ;
			{
				if (!(((NI)0) < readBytesX60gensym1__1)) goto LA13_;
				result += readBytesX60gensym1__1;
			}
			goto LA8_;
LA13_: ;
			{
				{
					NI32 T18_;
					NIM_BOOL T19_;
					T18_ = (NI32)0;
					T18_ = osLastError__stdZoserrors_u122();
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					T19_ = (NIM_BOOL)0;
					T19_ = contains__stdZsysrand_u35(TM__sT0fWggTrXhnxQ79bl9a8nHg_4, 2, ((int) (T18_)));
					if (!T19_) goto LA20_;
				}
				goto LA16_;
LA20_: ;
				{
					result = ((NI)-1);
					goto LA5;
				}
LA16_: ;
			}
LA8_: ;
		} LA6: ;
	} LA5: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, urandom__stdZsysrand_u121)(NU8* dest_p0, NI dest_p0Len_0) {
	NIM_BOOL result;
	NI ret_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_TRUE;
	ret_1 = urandomInternalImpl__stdZsysrand_u18(dest_p0, dest_p0Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(ret_1 < ((NI)0))) goto LA3_;
		result = NIM_FALSE;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
