/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pstd@sprivate@soscommon.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pstd@sprivate@soscommon.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__K6xUu89ae9bh8I0wWhnxZ25w tyTuple__K6xUu89ae9bh8I0wWhnxZ25w;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_PathComponent__19cEchTow8g9ctmD1o6pg6hA;
struct tyTuple__K6xUu89ae9bh8I0wWhnxZ25w {
	tyEnum_PathComponent__19cEchTow8g9ctmD1o6pg6hA Field0;
	NIM_BOOL Field1;
};
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename_p0) {
	NIM_BOOL result;
	struct stat res_1;
	NIM_BOOL T1_;
	int T2_;
{	nimZeroMem((void*)(&res_1), sizeof(struct stat));
	T1_ = (NIM_BOOL)0;
	T2_ = (int)0;
	T2_ = stat(nimToCStringConv(filename_p0), (&res_1));
	T1_ = (((NI32)0) <= T2_);
	if (!(T1_)) goto LA3_;
	T1_ = S_ISREG(res_1.st_mode);
LA3_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosdirExists)(NimStringV2 dir_p0) {
	NIM_BOOL result;
	struct stat res_1;
	NIM_BOOL T1_;
	int T2_;
	nimZeroMem((void*)(&res_1), sizeof(struct stat));
	T1_ = (NIM_BOOL)0;
	T2_ = (int)0;
	T2_ = stat(nimToCStringConv(dir_p0), (&res_1));
	T1_ = (((NI32)0) <= T2_);
	if (!(T1_)) goto LA3_;
	T1_ = S_ISDIR(res_1.st_mode);
LA3_: ;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__K6xUu89ae9bh8I0wWhnxZ25w, getSymlinkFileKind__stdZprivateZoscommon_u17)(NimStringV2 path_p0) {
	tyTuple__K6xUu89ae9bh8I0wWhnxZ25w result;
	struct stat s_1;
	tyEnum_PathComponent__19cEchTow8g9ctmD1o6pg6hA colontmp_;
	NIM_BOOL colontmp__2;
	nimZeroMem((void*)(&s_1), sizeof(struct stat));
	colontmp_ = ((tyEnum_PathComponent__19cEchTow8g9ctmD1o6pg6hA)1);
	colontmp__2 = NIM_FALSE;
	result.Field0 = colontmp_;
	result.Field1 = colontmp__2;
	{
		int T3_;
		T3_ = (int)0;
		T3_ = stat(nimToCStringConv(path_p0), (&s_1));
		if (!(T3_ == ((NI32)0))) goto LA4_;
		{
			NIM_BOOL T8_;
			tyEnum_PathComponent__19cEchTow8g9ctmD1o6pg6hA colontmp__3;
			NIM_BOOL colontmp__4;
			T8_ = (NIM_BOOL)0;
			T8_ = S_ISDIR(s_1.st_mode);
			if (!T8_) goto LA9_;
			colontmp__3 = ((tyEnum_PathComponent__19cEchTow8g9ctmD1o6pg6hA)3);
			colontmp__4 = NIM_FALSE;
			result.Field0 = colontmp__3;
			result.Field1 = colontmp__4;
		}
		goto LA6_;
LA9_: ;
		{
			NIM_BOOL T12_;
			tyEnum_PathComponent__19cEchTow8g9ctmD1o6pg6hA colontmp__5;
			NIM_BOOL colontmp__6;
			T12_ = (NIM_BOOL)0;
			T12_ = S_ISREG(s_1.st_mode);
			if (!!(T12_)) goto LA13_;
			colontmp__5 = ((tyEnum_PathComponent__19cEchTow8g9ctmD1o6pg6hA)1);
			colontmp__6 = NIM_TRUE;
			result.Field0 = colontmp__5;
			result.Field1 = colontmp__6;
		}
		goto LA6_;
LA13_: ;
LA6_: ;
	}
LA4_: ;
	return result;
}
