/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pstd@sprivate@sospaths2.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pstd@sprivate@sospaths2.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <unistd.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA;
typedef struct tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg tySequence__TM0VfWZgOhRIJ9bpQyFJFrg;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content;
typedef struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg tyTuple__7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg {
  NI len; tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__TM0VfWZgOhRIJ9bpQyFJFrg trace;
	Exception* up;
};
struct tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw {
	Exception Sup;
};
struct tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA {
	tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw Sup;
};
struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg {
	NimStringV2 Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content { NI cap; tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg data[SEQ_DECL_SIZE]; };
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__stdZprivateZospaths2_u49)(NimStringV2* result_p0, NI* state_p1, NimStringV2 tail_p2);
static N_INLINE(NIM_CHAR, X5BX5D___system_u8459)(NimStringV2 s_p0, NI i_p1);
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8511)(NimStringV2* s_p0, NI i_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2492)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u20)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2749)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, addNormalizePath__pureZpathnorm_u86)(NimStringV2 x_p0, NimStringV2* result_p1, NI* state_p2, NIM_CHAR dirSep_p3);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2743)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(NIM_BOOL, eqeq___system_u8988)(NCSTRING x_p0, NCSTRING y_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u122)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u119)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI, parentDirPos__stdZprivateZospaths2_u163)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normalizePath__pureZpathnorm_u150)(NimStringV2 path_p0, NIM_CHAR dirSep_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9036)(NimStringV2 s_p0, NI first_p1, NI last_p2);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9049)(NimStringV2 s_p0, NI first_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_2 = { 1 | NIM_STRLIT_FLAG, "/" };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_3 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_2};
extern TNimTypeV2 NTIv2__hxmI0FYjM9anPt7Bv1LM5TA_;
static const struct {
  NI cap; NIM_CHAR data[36+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_4 = { 36 | NIM_STRLIT_FLAG, "The specified root is not absolute: " };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_5 = {36, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_4};
static const struct {
  NI cap; NIM_CHAR data[37+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_6 = { 37 | NIM_STRLIT_FLAG, "ospaths2.nim(885, 21) `bufsize >= 0` " };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_7 = {37, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_6};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_8 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_9 = {0, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_8};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_10 = { 2 | NIM_STRLIT_FLAG, ".." };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_11 = {2, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_10};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__O1zDbSYyG8zQytyoZAh0dg_12 = { 1 | NIM_STRLIT_FLAG, "." };
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_13 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_12};
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_14 = {0, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_8};
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_15 = {1, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_12};
static const NimStringV2 TM__O1zDbSYyG8zQytyoZAh0dg_16 = {0, (NimStrPayload*)&TM__O1zDbSYyG8zQytyoZAh0dg_8};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4183;
static N_INLINE(NIM_CHAR, X5BX5D___system_u8459)(NimStringV2 s_p0, NI i_p1) {
	NIM_CHAR result;
	result = s_p0.p->data[(NI)(s_p0.len - i_p1)];
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2492(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8511)(NimStringV2* s_p0, NI i_p1) {
	NIM_CHAR* result;
	nimPrepareStrMutationV2((&(*s_p0)));
	result = (&(*s_p0).p->data[(NI)((*s_p0).len - i_p1)]);
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u20)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1) {
	NI i_1;
{	{
		if (!((*path_p0).len == ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	i_1 = (*path_p0).len;
	{
		while (1) {
			if (!(((NI)1) <= i_1)) goto LA6;
			{
				if (!(((NU8)((*path_p0).p->data[(NI)(i_1 - ((NI)1))])) == ((NU8)(47)) || ((NU8)((*path_p0).p->data[(NI)(i_1 - ((NI)1))])) == ((NU8)(47)))) goto LA9_;
				i_1 -= ((NI)1);
			}
			goto LA7_;
LA9_: ;
			{
				NIM_BOOL T12_;
				NIM_BOOL T13_;
				T12_ = (NIM_BOOL)0;
				T13_ = (NIM_BOOL)0;
				T13_ = ((NU8)((*path_p0).p->data[(NI)(i_1 - ((NI)1))]) == (NU8)(46));
				if (!(T13_)) goto LA14_;
				T13_ = (((NI)2) <= i_1);
LA14_: ;
				T12_ = T13_;
				if (!(T12_)) goto LA15_;
				T12_ = (((NU8)((*path_p0).p->data[(NI)(i_1 - ((NI)2))])) == ((NU8)(47)) || ((NU8)((*path_p0).p->data[(NI)(i_1 - ((NI)2))])) == ((NU8)(47)));
LA15_: ;
				if (!T12_) goto LA16_;
				i_1 -= ((NI)1);
			}
			goto LA7_;
LA16_: ;
			{
				goto LA5;
			}
LA7_: ;
		} LA6: ;
	} LA5: ;
	{
		if (!trailingSep_p1) goto LA21_;
		setLengthStrV2((&(*path_p0)), (i_1));
		nimAddCharV1((&(*path_p0)), 47);
	}
	goto LA19_;
LA21_: ;
	{
		if (!(((NI)0) < i_1)) goto LA24_;
		setLengthStrV2((&(*path_p0)), (i_1));
	}
	goto LA19_;
LA24_: ;
	{
		eqsink___system_u2749((&(*path_p0)), TM__O1zDbSYyG8zQytyoZAh0dg_3);
	}
LA19_: ;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4183);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__stdZprivateZospaths2_u49)(NimStringV2* result_p0, NI* state_p1, NimStringV2 tail_p2) {
	NIM_BOOL trailingSep_1;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_CHAR T4_;
	NIM_BOOL T6_;
	NIM_BOOL T8_;
	NIM_CHAR* T10_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (NIM_BOOL)0;
	T2_ = (NIM_BOOL)0;
	T2_ = (((NI)0) < tail_p2.len);
	if (!(T2_)) goto LA3_;
	T4_ = (NIM_CHAR)0;
	T4_ = X5BX5D___system_u8459(tail_p2, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (((NU8)(T4_)) == ((NU8)(47)) || ((NU8)(T4_)) == ((NU8)(47)));
LA3_: ;
	T1_ = T2_;
	if (T1_) goto LA5_;
	T6_ = (NIM_BOOL)0;
	T6_ = (tail_p2.len == ((NI)0));
	if (!(T6_)) goto LA7_;
	T8_ = (NIM_BOOL)0;
	T8_ = (((NI)0) < (*result_p0).len);
	if (!(T8_)) goto LA9_;
	T10_ = (NIM_CHAR*)0;
	T10_ = X5BX5D___system_u8511(result_p0, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T8_ = (((NU8)((*T10_))) == ((NU8)(47)) || ((NU8)((*T10_))) == ((NU8)(47)));
LA9_: ;
	T6_ = T8_;
LA7_: ;
	T1_ = T6_;
LA5_: ;
	trailingSep_1 = T1_;
	normalizePathEnd__stdZprivateZospaths2_u20(result_p0, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	addNormalizePath__pureZpathnorm_u86(tail_p2, result_p0, state_p1, 47);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	normalizePathEnd__stdZprivateZospaths2_u20(result_p0, trailingSep_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1) {
	NimStringV2 result;
	NI state_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = rawNewString(((NI)(head_p0.len + tail_p1.len)));
	state_1 = ((NI)0);
	joinPathImpl__stdZprivateZospaths2_u49((&result), (&state_1), head_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	joinPathImpl__stdZprivateZospaths2_u49((&result), (&state_1), tail_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringV2 path_p0) {
	NIM_BOOL result;
{	{
		if (!(path_p0.len == ((NI)0))) goto LA3_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA3_: ;
	result = ((NU8)(path_p0.p->data[((NI)0)]) == (NU8)(47));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, absolutePath__stdZprivateZospaths2_u359)(NimStringV2 path_p0, NimStringV2 root_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = nosisAbsolute(path_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T4_) goto LA5_;
		eqcopy___system_u2743((&result), path_p0);
	}
	goto LA2_;
LA5_: ;
	{
		{
			NIM_BOOL T10_;
			tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA* T13_;
			NimStringV2 T14_;
			T10_ = (NIM_BOOL)0;
			T10_ = nosisAbsolute(root_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T10_)) goto LA11_;
			T13_ = NIM_NIL;
			T13_ = (tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA*) nimNewObj(sizeof(tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA), NIM_ALIGNOF(tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA));
			(*T13_).Sup.Sup.Sup.m_type = (&NTIv2__hxmI0FYjM9anPt7Bv1LM5TA_);
			(*T13_).Sup.Sup.name = "ValueError";
			T14_.len = 0; T14_.p = NIM_NIL;
			T14_ = rawNewString(root_p1.len + 36);
appendString((&T14_), TM__O1zDbSYyG8zQytyoZAh0dg_5);
appendString((&T14_), root_p1);
			(*T13_).Sup.Sup.message = T14_;
			(*T13_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			raiseExceptionEx((Exception*)T13_, "ValueError", "absolutePath", "ospaths2.nim", 904);
goto BeforeRet_;
		}
LA11_: ;
		result = nosjoinPath(root_p1, path_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA2_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, eqeq___system_u8988)(NCSTRING x_p0, NCSTRING y_p1) {
	NIM_BOOL result;
	{
		if (!(((void*) (x_p0)) == ((void*) (y_p1)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T6_;
		T6_ = (NIM_BOOL)0;
		T6_ = (((void*) (x_p0)) == NIM_NIL);
		if (T6_) goto LA7_;
		T6_ = (((void*) (y_p1)) == NIM_NIL);
LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
LA8_: ;
	{
		int T11_;
		T11_ = (int)0;
		T11_ = strcmp(x_p0, y_p1);
		result = (T11_ == ((NI32)0));
	}
LA1_: ;
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetCurrentDir)(void) {
	NimStringV2 result;
	NI bufsize_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	bufsize_1 = ((NI)1024);
	result = mnewString((bufsize_1));
	{
		while (1) {
			{
				NCSTRING T5_;
				NIM_BOOL T6_;
				size_t T9_;
				T5_ = (NCSTRING)0;
				T5_ = getcwd(nimToCStringConv(result), bufsize_1);
				T6_ = (NIM_BOOL)0;
				T6_ = eqeq___system_u8988(T5_, ((NCSTRING) NIM_NIL));
				if (!!(T6_)) goto LA7_;
				T9_ = (size_t)0;
				T9_ = strlen(nimToCStringConv(result));
				setLengthStrV2((&result), ((NI) (T9_)));
				goto LA1;
			}
			goto LA3_;
LA7_: ;
			{
				NI32 err_1;
				err_1 = osLastError__stdZoserrors_u122();
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				{
					NimStringV2 T19_;
					if (!(err_1 == ((int)34))) goto LA13_;
					bufsize_1 = (NI)((NU64)(bufsize_1) << (NU64)(((NI)1) & (64 - 1)));
					{
						if (!!((((NI)0) <= bufsize_1))) goto LA17_;
						failedAssertImpl__stdZassertions_u95(TM__O1zDbSYyG8zQytyoZAh0dg_7);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA17_: ;
					T19_.len = 0; T19_.p = NIM_NIL;
					T19_ = mnewString((bufsize_1));
					eqsink___system_u2749((&result), T19_);
				}
				goto LA11_;
LA13_: ;
				{
					NI32 T21_;
					T21_ = (NI32)0;
					T21_ = osLastError__stdZoserrors_u122();
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					raiseOSError__stdZoserrors_u119(T21_, TM__O1zDbSYyG8zQytyoZAh0dg_9);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA11_: ;
			}
LA3_: ;
		}
	} LA1: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, parentDirPos__stdZprivateZospaths2_u163)(NimStringV2 path_p0) {
	NI result;
	NI q_1;
{	q_1 = ((NI)1);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)1) <= path_p0.len);
		if (!(T3_)) goto LA4_;
		T3_ = (((NU8)(path_p0.p->data[(NI)(path_p0.len - ((NI)1))])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[(NI)(path_p0.len - ((NI)1))])) == ((NU8)(47)));
LA4_: ;
		if (!T3_) goto LA5_;
		q_1 = ((NI)2);
	}
LA5_: ;
	{
		NI i_1;
		NI colontmp_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(path_p0.len - q_1);
		res_1 = colontmp_;
		{
			while (1) {
				if (!(((NI)0) <= res_1)) goto LA9;
				i_1 = ((NI) (res_1));
				{
					if (!(((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)))) goto LA12_;
					result = i_1;
					goto BeforeRet_;
				}
LA12_: ;
				res_1 -= ((NI)1);
			} LA9: ;
		}
	}
	result = ((NI)-1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisRootDir)(NimStringV2 path_p0) {
	NIM_BOOL result;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = parentDirPos__stdZprivateZospaths2_u163(path_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (T1_ < ((NI)0));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
{	result = NIM_FALSE;
	alen_1 = a_p0.len;
	blen_1 = b_p1.len;
	{
		if (!(alen_1 == blen_1)) goto LA3_;
		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosparentDir)(NimStringV2 path_p0) {
	NimStringV2 result;
	NI sepPos_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = normalizePath__pureZpathnorm_u150(path_p0, 47);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	sepPos_1 = parentDirPos__stdZprivateZospaths2_u163(result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NimStringV2 T5_;
		if (!(((NI)0) <= sepPos_1)) goto LA3_;
		T5_.len = 0; T5_.p = NIM_NIL;
		T5_ = substr__system_u9036(result, ((NI)0), sepPos_1);
		eqsink___system_u2749((&result), T5_);
		normalizePathEnd__stdZprivateZospaths2_u20((&result), NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T7_;
		NIM_BOOL T8_;
		NIM_BOOL T9_;
		NIM_CHAR* T13_;
		T7_ = (NIM_BOOL)0;
		T8_ = (NIM_BOOL)0;
		T9_ = (NIM_BOOL)0;
		T9_ = eqStrings(result, TM__O1zDbSYyG8zQytyoZAh0dg_11);
		if (T9_) goto LA10_;
		T9_ = eqStrings(result, TM__O1zDbSYyG8zQytyoZAh0dg_13);
LA10_: ;
		T8_ = T9_;
		if (T8_) goto LA11_;
		T8_ = (result.len == ((NI)0));
LA11_: ;
		T7_ = T8_;
		if (T7_) goto LA12_;
		T13_ = (NIM_CHAR*)0;
		T13_ = X5BX5D___system_u8511((&result), ((NI)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T7_ = (((NU8)((*T13_))) == ((NU8)(47)) || ((NU8)((*T13_))) == ((NU8)(47)));
LA12_: ;
		if (!T7_) goto LA14_;
		eqsink___system_u2749((&result), TM__O1zDbSYyG8zQytyoZAh0dg_14);
	}
	goto LA1_;
LA14_: ;
	{
		eqsink___system_u2749((&result), TM__O1zDbSYyG8zQytyoZAh0dg_15);
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, nossplitFile)(NimStringV2 path_p0, tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* Result) {
	NI namePos_1;
	NI dotPos_1;
	nimZeroMem((void*)Result, sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
	namePos_1 = ((NI)0);
	dotPos_1 = ((NI)0);
	{
		NI i_1;
		NI colontmp_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(path_p0.len - ((NI)1));
		res_1 = colontmp_;
		{
			while (1) {
				if (!(((NI)0) <= res_1)) goto LA3;
				i_1 = ((NI) (res_1));
				{
					NIM_BOOL T6_;
					T6_ = (NIM_BOOL)0;
					T6_ = (((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)));
					if (T6_) goto LA7_;
					T6_ = (i_1 == ((NI)0));
LA7_: ;
					if (!T6_) goto LA8_;
					{
						NI colontmpD_;
						NI colontmpD__2;
						NI T14_;
						NimStringV2 T21_;
						if (!(((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)))) goto LA12_;
						colontmpD_ = (NI)0;
						colontmpD__2 = (NI)0;
						T14_ = (NI)0;
						{
							NIM_BOOL T17_;
							T17_ = (NIM_BOOL)0;
							T17_ = NIM_LIKELY((((NI)1) <= i_1));
							if (!T17_) goto LA18_;
							colontmpD_ = (NI)(i_1 - ((NI)1));
							T14_ = colontmpD_;
						}
						goto LA15_;
LA18_: ;
						{
							colontmpD__2 = ((NI)0);
							T14_ = colontmpD__2;
						}
LA15_: ;
						T21_.len = 0; T21_.p = NIM_NIL;
						T21_ = substr__system_u9036(path_p0, ((NI)0), T14_);
						eqsink___system_u2749((&(*Result).Field0), T21_);
						namePos_1 = (NI)(i_1 + ((NI)1));
					}
LA12_: ;
					{
						NimStringV2 T26_;
						NimStringV2 T27_;
						if (!(i_1 < dotPos_1)) goto LA24_;
						T26_.len = 0; T26_.p = NIM_NIL;
						T26_ = substr__system_u9036(path_p0, namePos_1, (NI)(dotPos_1 - ((NI)1)));
						eqsink___system_u2749((&(*Result).Field1), T26_);
						T27_.len = 0; T27_.p = NIM_NIL;
						T27_ = substr__system_u9049(path_p0, dotPos_1);
						eqsink___system_u2749((&(*Result).Field2), T27_);
					}
					goto LA22_;
LA24_: ;
					{
						NimStringV2 T29_;
						T29_.len = 0; T29_.p = NIM_NIL;
						T29_ = substr__system_u9049(path_p0, namePos_1);
						eqsink___system_u2749((&(*Result).Field1), T29_);
					}
LA22_: ;
					goto LA1;
				}
				goto LA4_;
LA8_: ;
				{
					NIM_BOOL T31_;
					NIM_BOOL T32_;
					NIM_BOOL T33_;
					NIM_BOOL T34_;
					NIM_BOOL T35_;
					T31_ = (NIM_BOOL)0;
					T32_ = (NIM_BOOL)0;
					T33_ = (NIM_BOOL)0;
					T34_ = (NIM_BOOL)0;
					T35_ = (NIM_BOOL)0;
					T35_ = ((NU8)(path_p0.p->data[i_1]) == (NU8)(46));
					if (!(T35_)) goto LA36_;
					T35_ = (((NI)0) < i_1);
LA36_: ;
					T34_ = T35_;
					if (!(T34_)) goto LA37_;
					T34_ = (i_1 < (NI)(path_p0.len - ((NI)1)));
LA37_: ;
					T33_ = T34_;
					if (!(T33_)) goto LA38_;
					T33_ = !((((NU8)(path_p0.p->data[(NI)(i_1 - ((NI)1))])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[(NI)(i_1 - ((NI)1))])) == ((NU8)(47))));
LA38_: ;
					T32_ = T33_;
					if (!(T32_)) goto LA39_;
					T32_ = !(((NU8)(path_p0.p->data[(NI)(i_1 + ((NI)1))]) == (NU8)(46)));
LA39_: ;
					T31_ = T32_;
					if (!(T31_)) goto LA40_;
					T31_ = (dotPos_1 == ((NI)0));
LA40_: ;
					if (!T31_) goto LA41_;
					dotPos_1 = i_1;
				}
				goto LA4_;
LA41_: ;
LA4_: ;
				res_1 -= ((NI)1);
			} LA3: ;
		}
	} LA1: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZos_u197)(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* dest_p0) {
	if ((*dest_p0).Field0.p && !((*dest_p0).Field0.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field0.p);
}
	if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field1.p);
}
	if ((*dest_p0).Field2.p && !((*dest_p0).Field2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field2.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, nossplitPath)(NimStringV2 path_p0, tyTuple__UV3llMMYFckfui8YMBuUZA* Result) {
	NI sepPos_1;
	nimZeroMem((void*)Result, sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
	sepPos_1 = ((NI)-1);
	{
		NI i_1;
		NI colontmp_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(path_p0.len - ((NI)1));
		res_1 = colontmp_;
		{
			while (1) {
				if (!(((NI)0) <= res_1)) goto LA3;
				i_1 = ((NI) (res_1));
				{
					if (!(((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[i_1])) == ((NU8)(47)))) goto LA6_;
					sepPos_1 = i_1;
					goto LA1;
				}
LA6_: ;
				res_1 -= ((NI)1);
			} LA3: ;
		}
	} LA1: ;
	{
		NI colontmpD_;
		NI colontmpD__2;
		NI T12_;
		NimStringV2 T19_;
		NimStringV2 T20_;
		if (!(((NI)0) <= sepPos_1)) goto LA10_;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		T12_ = (NI)0;
		{
			NIM_BOOL T15_;
			T15_ = (NIM_BOOL)0;
			T15_ = NIM_LIKELY((((NI)1) <= sepPos_1));
			if (!T15_) goto LA16_;
			colontmpD_ = (NI)(sepPos_1 - ((NI)1));
			T12_ = colontmpD_;
		}
		goto LA13_;
LA16_: ;
		{
			colontmpD__2 = ((NI)0);
			T12_ = colontmpD__2;
		}
LA13_: ;
		T19_.len = 0; T19_.p = NIM_NIL;
		T19_ = substr__system_u9036(path_p0, ((NI)0), T12_);
		eqsink___system_u2749((&(*Result).Field0), T19_);
		T20_.len = 0; T20_.p = NIM_NIL;
		T20_ = substr__system_u9049(path_p0, (NI)(sepPos_1 + ((NI)1)));
		eqsink___system_u2749((&(*Result).Field1), T20_);
	}
	goto LA8_;
LA10_: ;
	{
		eqsink___system_u2749((&(*Result).Field0), TM__O1zDbSYyG8zQytyoZAh0dg_16);
		eqcopy___system_u2743((&(*Result).Field1), path_p0);
	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZospaths2_u303)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest_p0) {
	if ((*dest_p0).Field0.p && !((*dest_p0).Field0.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field0.p);
}
	if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field1.p);
}
}
