/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pstd@sassertions.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pstd@sassertions.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA;
typedef struct tyObject_Defect__EL9aN6agFLgcb8D9bbKrC9cFA tyObject_Defect__EL9aN6agFLgcb8D9bbKrC9cFA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg tySequence__TM0VfWZgOhRIJ9bpQyFJFrg;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content;
typedef struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg {
  NI len; tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__TM0VfWZgOhRIJ9bpQyFJFrg trace;
	Exception* up;
};
struct tyObject_Defect__EL9aN6agFLgcb8D9bbKrC9cFA {
	Exception Sup;
};
struct tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA {
	tyObject_Defect__EL9aN6agFLgcb8D9bbKrC9cFA Sup;
};
struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content { NI cap; tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg data[SEQ_DECL_SIZE]; };
static N_INLINE(void, sysFatal__stdZassertions_u30)(NimStringV2 message_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2746)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u28)(NimStringV2 msg_p0);
extern TNimTypeV2 NTIv2__z1bPK6E04CoQaHIh4Rm5rA_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4183;
static N_INLINE(void, sysFatal__stdZassertions_u30)(NimStringV2 message_p1) {
	NimStringV2 colontmpD_;
	tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA* T1_;
{	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA*) nimNewObj(sizeof(tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA), NIM_ALIGNOF(tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__z1bPK6E04CoQaHIh4Rm5rA_);
	(*T1_).Sup.Sup.name = "AssertionDefect";
	colontmpD_ = eqdup___system_u2746(message_p1);
	(*T1_).Sup.Sup.message = colontmpD_;
	raiseExceptionEx((Exception*)T1_, "AssertionDefect", "sysFatal", "fatal.nim", 62);
goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4183);
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseAssert__stdZassertions_u28)(NimStringV2 msg_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	sysFatal__stdZassertions_u30(msg_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	raiseAssert__stdZassertions_u28(msg_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
