/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pstrutils.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pstrutils.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA;
typedef struct tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg tySequence__TM0VfWZgOhRIJ9bpQyFJFrg;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content;
typedef struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg {
  NI len; tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__TM0VfWZgOhRIJ9bpQyFJFrg trace;
	Exception* up;
};
struct tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw {
	Exception Sup;
};
struct tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA {
	tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw Sup;
};
typedef NI tyArray__9cc9aPiDa8VaWjVcFLabEDZQ[256];
typedef NU8 tyEnum_FloatFormatMode__hNdXmiskUMJ5uyhuQ9bFwtg;
typedef NIM_CHAR tyArray__Dz6OE1kpzz8bnx9batFy1Cw[6];
typedef NIM_CHAR tyArray__WALV5e0ysjOIjCclEgOBNg[2501];
typedef NIM_CHAR tyArray__wCnDC9aGS9a8hjCJBWACIqXQ[3];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content { NI cap; tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9036)(NimStringV2 s_p0, NI first_p1, NI last_p2);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, substrEq__pureZstrutils_u256)(NimStringV2 s_p0, NI pos_p1, NimStringV2 substr_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2749)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2740)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2492)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(NI, parseInt__pureZparseutils_u981)(NimStringV2 s_p0, NI* number_p1, NI start_p2);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1);
N_LIB_PRIVATE N_NIMCALL(void, fill__pureZstrutils_u1566)(NI* a_p0, NI a_p0Len_0, NI value_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NI, parseFloat__pureZparseutils_u1006)(NimStringV2 s_p0, NF* number_p1, NI start_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToUpperAsciiChar)(NIM_CHAR c_p0);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHexImpl__pureZstrutils_u777)(NU64 x_p0, NI len_p1, NIM_BOOL handleNegative_p2);
extern TNimTypeV2 NTIv2__hxmI0FYjM9anPt7Bv1LM5TA_;
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_2 = { 17 | NIM_STRLIT_FLAG, "invalid integer: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_3 = {17, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_2};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_4 = { 15 | NIM_STRLIT_FLAG, "invalid float: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_5 = {15, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_4};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_6 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_7 = {0, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_6};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_8 = { 16 | NIM_STRLIT_FLAG, "0123456789ABCDEF" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_9 = {16, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_8};
N_LIB_PRIVATE NIM_CONST tyArray__wCnDC9aGS9a8hjCJBWACIqXQ floatFormatToChar__pureZstrutils_u2191 = {103,
102,
101}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4183;
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3) {
	NimStringV2 result;
	NI first_1;
	NI last_1;
	first_1 = ((NI)0);
	last_1 = (NI)(s_p0.len - ((NI)1));
	{
		if (!leading_p1) goto LA3_;
		{
			while (1) {
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				T7_ = (first_1 <= last_1);
				if (!(T7_)) goto LA8_;
				T7_ = ((chars_p3[(NU)((((NU8)(s_p0.p->data[first_1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[first_1]))))&7U)))!=0);
LA8_: ;
				if (!T7_) goto LA6;
				first_1 += ((NI)1);
			} LA6: ;
		}
	}
LA3_: ;
	{
		if (!trailing_p2) goto LA11_;
		{
			while (1) {
				NIM_BOOL T15_;
				T15_ = (NIM_BOOL)0;
				T15_ = (first_1 <= last_1);
				if (!(T15_)) goto LA16_;
				T15_ = ((chars_p3[(NU)((((NU8)(s_p0.p->data[last_1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[last_1]))))&7U)))!=0);
LA16_: ;
				if (!T15_) goto LA14;
				last_1 -= ((NI)1);
			} LA14: ;
		}
	}
LA11_: ;
	result = substr__system_u9036(s_p0, first_1, last_1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringV2 s_p0, NimStringV2 prefix_p1) {
	NIM_BOOL result;
	NI prefixLenX60gensym135__1;
	NI sLenX60gensym135__1;
	NI iX60gensym135__1;
{	result = NIM_FALSE;
	prefixLenX60gensym135__1 = prefix_p1.len;
	sLenX60gensym135__1 = s_p0.len;
	iX60gensym135__1 = ((NI)0);
	{
		while (1) {
			{
				if (!(prefixLenX60gensym135__1 <= iX60gensym135__1)) goto LA5_;
				result = NIM_TRUE;
				goto BeforeRet_;
			}
LA5_: ;
			{
				NIM_BOOL T9_;
				T9_ = (NIM_BOOL)0;
				T9_ = (sLenX60gensym135__1 <= iX60gensym135__1);
				if (T9_) goto LA10_;
				T9_ = !(((NU8)(s_p0.p->data[iX60gensym135__1]) == (NU8)(prefix_p1.p->data[iX60gensym135__1])));
LA10_: ;
				if (!T9_) goto LA11_;
				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA11_: ;
			iX60gensym135__1 += ((NI)1);
		}
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI length_1;
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	result = ((NI)-1);
	{
		if (!(last_p3 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p0.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p3;
		last_2 = colontmpD__2;
	}
LA1_: ;
	length_1 = (NI)((NI)(last_2 - start_p2) + ((NI)1));
	{
		void* found_1;
		if (!(((NI)0) < length_1)) goto LA8_;
		found_1 = memchr(((void*) ((&s_p0.p->data[start_p2]))), ((int) (((NU8)(sub_p1)))), ((size_t) (length_1)));
		{
			if (!!((found_1 == 0))) goto LA12_;
			result = minuspercent___system_u813(((NI) (ptrdiff_t) (found_1)), ((NI) (nimToCStringConv(s_p0))));
			goto BeforeRet_;
		}
LA12_: ;
	}
LA8_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, substrEq__pureZstrutils_u256)(NimStringV2 s_p0, NI pos_p1, NimStringV2 substr_p2) {
	NIM_BOOL result;
	NIM_BOOL colontmpD_;
	NIM_BOOL colontmpD__2;
	NI length_1;
	colontmpD_ = (NIM_BOOL)0;
	colontmpD__2 = (NIM_BOOL)0;
	length_1 = substr_p2.len;
	{
		NI i_1;
		if (!(((NI)0) < length_1)) goto LA3_;
		i_1 = ((NI)0);
		{
			while (1) {
				NIM_BOOL T7_;
				NIM_BOOL T8_;
				T7_ = (NIM_BOOL)0;
				T8_ = (NIM_BOOL)0;
				T8_ = (i_1 < length_1);
				if (!(T8_)) goto LA9_;
				T8_ = ((NI)(pos_p1 + i_1) < s_p0.len);
LA9_: ;
				T7_ = T8_;
				if (!(T7_)) goto LA10_;
				T7_ = ((NU8)(s_p0.p->data[(NI)(pos_p1 + i_1)]) == (NU8)(substr_p2.p->data[i_1]));
LA10_: ;
				if (!T7_) goto LA6;
				i_1 += ((NI)1);
			} LA6: ;
		}
		colontmpD_ = (i_1 == length_1);
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = NIM_FALSE;
		result = colontmpD__2;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4183);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitString)(NimStringV2 s_p0, NimStringV2 sep_p1, NI maxsplit_p2) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2 xX60gensym69__1;
		NI colontmpD_;
		NI colontmpD__2;
		NI sepLen_1;
		NI lastX60gensym41__1;
		NI splitsX60gensym41__1;
		xX60gensym69__1.len = 0; xX60gensym69__1.p = NIM_NIL;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		{
			if (!(sep_p1.len == ((NI)0))) goto LA5_;
			colontmpD_ = ((NI)1);
			sepLen_1 = colontmpD_;
		}
		goto LA3_;
LA5_: ;
		{
			colontmpD__2 = sep_p1.len;
			sepLen_1 = colontmpD__2;
		}
LA3_: ;
		lastX60gensym41__1 = ((NI)0);
		splitsX60gensym41__1 = maxsplit_p2;
		{
			while (1) {
				NI firstX60gensym41__1;
				NimStringV2 T19_;
				NimStringV2 blitTmp_1;
				if (!(lastX60gensym41__1 <= s_p0.len)) goto LA9;
				firstX60gensym41__1 = lastX60gensym41__1;
				{
					while (1) {
						NIM_BOOL T12_;
						NIM_BOOL T14_;
						T12_ = (NIM_BOOL)0;
						T12_ = (lastX60gensym41__1 < s_p0.len);
						if (!(T12_)) goto LA13_;
						T14_ = (NIM_BOOL)0;
						T14_ = substrEq__pureZstrutils_u256(s_p0, lastX60gensym41__1, sep_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
						T12_ = !(T14_);
LA13_: ;
						if (!T12_) goto LA11;
						lastX60gensym41__1 += ((NI)1);
					} LA11: ;
				}
				{
					if (!(splitsX60gensym41__1 == ((NI)0))) goto LA17_;
					lastX60gensym41__1 = s_p0.len;
				}
LA17_: ;
				T19_.len = 0; T19_.p = NIM_NIL;
				T19_ = substr__system_u9036(s_p0, firstX60gensym41__1, (NI)(lastX60gensym41__1 - ((NI)1)));
				eqsink___system_u2749((&xX60gensym69__1), T19_);
				blitTmp_1 = xX60gensym69__1;
				eqwasMoved___system_u2740((&xX60gensym69__1));
				add__stdZenumutils_u70((&result), blitTmp_1);
				{
					if (!(splitsX60gensym41__1 == ((NI)0))) goto LA22_;
					goto LA8;
				}
LA22_: ;
				splitsX60gensym41__1 -= ((NI)1);
				lastX60gensym41__1 += sepLen_1;
			} LA9: ;
		} LA8: ;
		{
			LA2_:;
		}
		{
			if (xX60gensym69__1.p && !(xX60gensym69__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(xX60gensym69__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2492(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	{
		if (!(((NU8)(c_p0)) >= ((NU8)(65)) && ((NU8)(c_p0)) <= ((NU8)(90)))) goto LA3_;
		result = ((NIM_CHAR) ((NU8)(((NU8) (((NU8)(c_p0)))) ^ ((NU8)32))));
	}
	goto LA1_;
LA3_: ;
	{
		result = c_p0;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToLowerAsciiStr)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = mnewString((s_p0.len));
	{
		NI iX60gensym7__1;
		NI colontmp_;
		NI res_1;
		iX60gensym7__1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(s_p0.len - ((NI)1));
		res_1 = ((NI)0);
		{
			while (1) {
				NIM_CHAR T4_;
				if (!(res_1 <= colontmp_)) goto LA3;
				iX60gensym7__1 = ((NI) (res_1));
				nimPrepareStrMutationV2((&result));
				T4_ = (NIM_CHAR)0;
				T4_ = nsuToLowerAsciiChar(s_p0.p->data[iX60gensym7__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result.p->data[iX60gensym7__1] = T4_;
				res_1 += ((NI)1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringV2 s_p0) {
	NI result;
	NI L_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = ((NI)0);
	L_1 = parseInt__pureZparseutils_u981(s_p0, (&result), ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA* T7_;
		NimStringV2 T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L_1 == s_p0.len));
		if (T3_) goto LA4_;
		T3_ = (L_1 == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA*) nimNewObj(sizeof(tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA), NIM_ALIGNOF(tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__hxmI0FYjM9anPt7Bv1LM5TA_);
		(*T7_).Sup.Sup.name = "ValueError";
		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(s_p0.len + 17);
appendString((&T8_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_3);
appendString((&T8_), s_p0);
		(*T7_).Sup.Sup.message = T8_;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseInt", "strutils.nim", 1160);
goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitChar)(NimStringV2 s_p0, NIM_CHAR sep_p1, NI maxsplit_p2) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2 xX60gensym67__1;
		NI lastX60gensym34__1;
		NI splitsX60gensym34__1;
		xX60gensym67__1.len = 0; xX60gensym67__1.p = NIM_NIL;
		lastX60gensym34__1 = ((NI)0);
		splitsX60gensym34__1 = maxsplit_p2;
		{
			while (1) {
				NI firstX60gensym34__1;
				NimStringV2 T13_;
				NimStringV2 blitTmp_1;
				if (!(lastX60gensym34__1 <= s_p0.len)) goto LA4;
				firstX60gensym34__1 = lastX60gensym34__1;
				{
					while (1) {
						NIM_BOOL T7_;
						T7_ = (NIM_BOOL)0;
						T7_ = (lastX60gensym34__1 < s_p0.len);
						if (!(T7_)) goto LA8_;
						T7_ = !(((NU8)(s_p0.p->data[lastX60gensym34__1]) == (NU8)(sep_p1)));
LA8_: ;
						if (!T7_) goto LA6;
						lastX60gensym34__1 += ((NI)1);
					} LA6: ;
				}
				{
					if (!(splitsX60gensym34__1 == ((NI)0))) goto LA11_;
					lastX60gensym34__1 = s_p0.len;
				}
LA11_: ;
				T13_.len = 0; T13_.p = NIM_NIL;
				T13_ = substr__system_u9036(s_p0, firstX60gensym34__1, (NI)(lastX60gensym34__1 - ((NI)1)));
				eqsink___system_u2749((&xX60gensym67__1), T13_);
				blitTmp_1 = xX60gensym67__1;
				eqwasMoved___system_u2740((&xX60gensym67__1));
				add__stdZenumutils_u70((&result), blitTmp_1);
				{
					if (!(splitsX60gensym34__1 == ((NI)0))) goto LA16_;
					goto LA3;
				}
LA16_: ;
				splitsX60gensym34__1 -= ((NI)1);
				lastX60gensym34__1 += ((NI)1);
			} LA4: ;
		} LA3: ;
		{
			LA2_:;
		}
		{
			if (xX60gensym67__1.p && !(xX60gensym67__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(xX60gensym67__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitWhitespace)(NimStringV2 s_p0, NI maxsplit_p1) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2 xX60gensym74__1;
		NI lastX60gensym59__1;
		NI splitsX60gensym59__1;
		xX60gensym74__1.len = 0; xX60gensym74__1.p = NIM_NIL;
		lastX60gensym59__1 = ((NI)0);
		splitsX60gensym59__1 = maxsplit_p1;
		{
			while (1) {
				NI firstX60gensym59__1;
				if (!(lastX60gensym59__1 < s_p0.len)) goto LA4;
				{
					while (1) {
						NIM_BOOL T7_;
						T7_ = (NIM_BOOL)0;
						T7_ = (lastX60gensym59__1 < s_p0.len);
						if (!(T7_)) goto LA8_;
						T7_ = (((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(32)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(9)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(11)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(13)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(10)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(12)));
LA8_: ;
						if (!T7_) goto LA6;
						lastX60gensym59__1 += ((NI)1);
					} LA6: ;
				}
				firstX60gensym59__1 = lastX60gensym59__1;
				{
					while (1) {
						NIM_BOOL T11_;
						T11_ = (NIM_BOOL)0;
						T11_ = (lastX60gensym59__1 < s_p0.len);
						if (!(T11_)) goto LA12_;
						T11_ = !((((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(32)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(9)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(11)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(13)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(10)) || ((NU8)(s_p0.p->data[lastX60gensym59__1])) == ((NU8)(12))));
LA12_: ;
						if (!T11_) goto LA10;
						lastX60gensym59__1 += ((NI)1);
					} LA10: ;
				}
				{
					NimStringV2 T21_;
					NimStringV2 blitTmp_1;
					if (!(firstX60gensym59__1 <= (NI)(lastX60gensym59__1 - ((NI)1)))) goto LA15_;
					{
						if (!(splitsX60gensym59__1 == ((NI)0))) goto LA19_;
						lastX60gensym59__1 = s_p0.len;
					}
LA19_: ;
					T21_.len = 0; T21_.p = NIM_NIL;
					T21_ = substr__system_u9036(s_p0, firstX60gensym59__1, (NI)(lastX60gensym59__1 - ((NI)1)));
					eqsink___system_u2749((&xX60gensym74__1), T21_);
					blitTmp_1 = xX60gensym74__1;
					eqwasMoved___system_u2740((&xX60gensym74__1));
					add__stdZenumutils_u70((&result), blitTmp_1);
					{
						if (!(splitsX60gensym59__1 == ((NI)0))) goto LA24_;
						goto LA3;
					}
LA24_: ;
					splitsX60gensym59__1 -= ((NI)1);
				}
LA15_: ;
			} LA4: ;
		} LA3: ;
		{
			LA2_:;
		}
		{
			if (xX60gensym74__1.p && !(xX60gensym74__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(xX60gensym74__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuIsAlphaNumericChar)(NIM_CHAR c_p0) {
	NIM_BOOL result;
{	result = (((NU8)(c_p0)) >= ((NU8)(48)) && ((NU8)(c_p0)) <= ((NU8)(57)) || ((NU8)(c_p0)) >= ((NU8)(65)) && ((NU8)(c_p0)) <= ((NU8)(90)) || ((NU8)(c_p0)) >= ((NU8)(97)) && ((NU8)(c_p0)) <= ((NU8)(122)));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI subLast_1;
	NI skip_1;
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	{
		if (!(last_p4 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p1.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p4;
		last_2 = colontmpD__2;
	}
LA1_: ;
	subLast_1 = (NI)(sub_p2.len - ((NI)1));
	{
		if (!(subLast_1 == ((NI)-1))) goto LA8_;
		result = start_p3;
		goto BeforeRet_;
	}
LA8_: ;
	result = ((NI)-1);
	skip_1 = start_p3;
	{
		while (1) {
			NI i_1;
			if (!(subLast_1 <= (NI)(last_2 - skip_1))) goto LA11;
			i_1 = subLast_1;
			{
				while (1) {
					if (!((NU8)(s_p1.p->data[(NI)(skip_1 + i_1)]) == (NU8)(sub_p2.p->data[i_1]))) goto LA13;
					{
						if (!(i_1 == ((NI)0))) goto LA16_;
						result = skip_1;
						goto BeforeRet_;
					}
LA16_: ;
					i_1 -= ((NI)1);
				} LA13: ;
			}
			skip_1 += a_p0[(((NU8)(s_p1.p->data[(NI)(skip_1 + subLast_1)])))- 0];
		} LA11: ;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1) {
	NI m_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	m_1 = sub_p1.len;
	fill__pureZstrutils_u1566(a_p0, 256, m_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i_1;
		NI colontmp_;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(m_1 - ((NI)1));
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA3;
				i_1 = i_2;
				a_p0[(((NU8)(sub_p1.p->data[i_1])))- 0] = (NI)((NI)(m_1 - ((NI)1)) - i_1);
				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nsuInitSkipTable(Result, sub_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3) {
	NI result;
	NI subLen_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		if (!((NI)(s_p0.len - start_p2) < sub_p1.len)) goto LA3_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA3_: ;
	{
		if (!(sub_p1.len == ((NI)1))) goto LA7_;
		result = nsuFindChar(s_p0, sub_p1.p->data[((NI)0)], start_p2, last_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA7_: ;
	subLen_1 = sub_p1.len;
	{
		NIM_BOOL T11_;
		NIM_BOOL T12_;
		NI colontmpD_;
		NI colontmpD__2;
		void* found_1;
		T11_ = (NIM_BOOL)0;
		T12_ = (NIM_BOOL)0;
		T12_ = (last_p3 < ((NI)0));
		if (!(T12_)) goto LA13_;
		T12_ = (start_p2 < s_p0.len);
LA13_: ;
		T11_ = T12_;
		if (!(T11_)) goto LA14_;
		T11_ = !((subLen_1 == ((NI)0)));
LA14_: ;
		if (!T11_) goto LA15_;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		found_1 = memmem(((void*) ((&s_p0.p->data[start_p2]))), ((size_t) ((NI)(s_p0.len - start_p2))), ((void*) (nimToCStringConv(sub_p1))), ((size_t) (subLen_1)));
		{
			if (!!((found_1 == 0))) goto LA19_;
			colontmpD_ = minuspercent___system_u813(((NI) (ptrdiff_t) (found_1)), ((NI) (nimToCStringConv(s_p0))));
			result = colontmpD_;
		}
		goto LA17_;
LA19_: ;
		{
			colontmpD__2 = ((NI)-1);
			result = colontmpD__2;
		}
LA17_: ;
	}
	goto LA9_;
LA15_: ;
	{
		tyArray__9cc9aPiDa8VaWjVcFLabEDZQ T23_;
		nimZeroMem((void*)T23_, sizeof(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ));
		nsuInitNewSkipTable(sub_p1, T23_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = nsuFindStrA(T23_, s_p0, sub_p1, start_p2, last_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1832)(NimStringV2 s_p0, NimStringV2 sub_p1) {
	NIM_BOOL result;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = nsuFindStr(s_p0, sub_p1, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, nsuParseFloat)(NimStringV2 s_p0) {
	NF result;
	NI L_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0.0;
	L_1 = parseFloat__pureZparseutils_u1006(s_p0, (&result), ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA* T7_;
		NimStringV2 T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L_1 == s_p0.len));
		if (T3_) goto LA4_;
		T3_ = (L_1 == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA*) nimNewObj(sizeof(tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA), NIM_ALIGNOF(tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__hxmI0FYjM9anPt7Bv1LM5TA_);
		(*T7_).Sup.Sup.name = "ValueError";
		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(s_p0.len + 15);
appendString((&T8_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_5);
appendString((&T8_), s_p0);
		(*T7_).Sup.Sup.message = T8_;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseFloat", "strutils.nim", 1202);
goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatChar)(NIM_CHAR c_p0, NI count_p1) {
	NimStringV2 result;
	result = mnewString(count_p1);
	{
		NI i_1;
		NI colontmp_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(count_p1 - ((NI)1));
		res_1 = ((NI)0);
		{
			while (1) {
				if (!(res_1 <= colontmp_)) goto LA3;
				i_1 = ((NI) (res_1));
				nimPrepareStrMutationV2((&result));
				result.p->data[i_1] = c_p0;
				res_1 += ((NI)1);
			} LA3: ;
		}
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatBiggestFloat)(NF f_p0, tyEnum_FloatFormatMode__hNdXmiskUMJ5uyhuQ9bFwtg format_p1, NI precision_p2, NIM_CHAR decimalSep_p3) {
	NimStringV2 result;
	tyArray__Dz6OE1kpzz8bnx9batFy1Cw frmtstr_1;
	tyArray__WALV5e0ysjOIjCclEgOBNg buf_1;
	int L_1;
	result.len = 0; result.p = NIM_NIL;
	L_1 = (int)0;
	frmtstr_1[(((NI)0))- 0] = 37;
	{
		if (!(((NI)0) <= precision_p2)) goto LA3_;
		frmtstr_1[(((NI)1))- 0] = 35;
		frmtstr_1[(((NI)2))- 0] = 46;
		frmtstr_1[(((NI)3))- 0] = 42;
		frmtstr_1[(((NI)4))- 0] = floatFormatToChar__pureZstrutils_u2191[(format_p1)- 0];
		frmtstr_1[(((NI)5))- 0] = 0;
		L_1 = snprintf(((NCSTRING) (buf_1)), ((size_t)2501), ((NCSTRING) (frmtstr_1)), precision_p2, f_p0);
	}
	goto LA1_;
LA3_: ;
	{
		frmtstr_1[(((NI)1))- 0] = floatFormatToChar__pureZstrutils_u2191[(format_p1)- 0];
		frmtstr_1[(((NI)2))- 0] = 0;
		L_1 = snprintf(((NCSTRING) (buf_1)), ((size_t)2501), ((NCSTRING) (frmtstr_1)), f_p0);
	}
LA1_: ;
	result = mnewString(((NI) (L_1)));
	{
		NI32 i_1;
		NI32 res_1;
		i_1 = (NI32)0;
		res_1 = ((NI32)0);
		{
			while (1) {
				if (!(res_1 < L_1)) goto LA8;
				i_1 = res_1;
				{
					if (!(((NU8)(buf_1[(i_1)- 0])) == ((NU8)(46)) || ((NU8)(buf_1[(i_1)- 0])) == ((NU8)(44)))) goto LA11_;
					nimPrepareStrMutationV2((&result));
					result.p->data[i_1] = decimalSep_p3;
				}
				goto LA9_;
LA11_: ;
				{
					nimPrepareStrMutationV2((&result));
					result.p->data[i_1] = buf_1[(i_1)- 0];
				}
LA9_: ;
				res_1 += ((NI)1);
			} LA8: ;
		}
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToUpperAsciiChar)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	{
		if (!(((NU8)(c_p0)) >= ((NU8)(97)) && ((NU8)(c_p0)) <= ((NU8)(122)))) goto LA3_;
		result = ((NIM_CHAR) ((NU8)(((NU8) (((NU8)(c_p0)))) ^ ((NU8)32))));
	}
	goto LA1_;
LA3_: ;
	{
		result = c_p0;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToUpperAsciiStr)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = mnewString((s_p0.len));
	{
		NI iX60gensym11__1;
		NI colontmp_;
		NI res_1;
		iX60gensym11__1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(s_p0.len - ((NI)1));
		res_1 = ((NI)0);
		{
			while (1) {
				NIM_CHAR T4_;
				if (!(res_1 <= colontmp_)) goto LA3;
				iX60gensym11__1 = ((NI) (res_1));
				nimPrepareStrMutationV2((&result));
				T4_ = (NIM_CHAR)0;
				T4_ = nsuToUpperAsciiChar(s_p0.p->data[iX60gensym11__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result.p->data[iX60gensym11__1] = T4_;
				res_1 += ((NI)1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringV2 s_p0, NimStringV2 suffix_p1) {
	NIM_BOOL result;
	NI suffixLenX60gensym142__1;
	NI sLenX60gensym142__1;
	NI iX60gensym142__1;
	NI jX60gensym142__1;
{	result = NIM_FALSE;
	suffixLenX60gensym142__1 = suffix_p1.len;
	sLenX60gensym142__1 = s_p0.len;
	iX60gensym142__1 = ((NI)0);
	jX60gensym142__1 = (NI)(sLenX60gensym142__1 - suffixLenX60gensym142__1);
	{
		while (1) {
			NIM_BOOL T3_;
			T3_ = (NIM_BOOL)0;
			T3_ = (((NI)0) <= (NI)(iX60gensym142__1 + jX60gensym142__1));
			if (!(T3_)) goto LA4_;
			T3_ = ((NI)(iX60gensym142__1 + jX60gensym142__1) < sLenX60gensym142__1);
LA4_: ;
			if (!T3_) goto LA2;
			{
				if (!!(((NU8)(s_p0.p->data[(NI)(iX60gensym142__1 + jX60gensym142__1)]) == (NU8)(suffix_p1.p->data[iX60gensym142__1])))) goto LA7_;
				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA7_: ;
			iX60gensym142__1 += ((NI)1);
		} LA2: ;
	}
	{
		if (!(suffixLenX60gensym142__1 <= iX60gensym142__1)) goto LA11_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
LA11_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 sep_p1) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	{
		NI L_1;
		if (!(((NI)0) < a_p0Len_0)) goto LA3_;
		L_1 = (NI)(sep_p1.len * (NI)(a_p0Len_0 - ((NI)1)));
		{
			NI i_1;
			NI colontmp_;
			NI res_1;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (a_p0Len_0-1);
			res_1 = ((NI)0);
			{
				while (1) {
					if (!(res_1 <= colontmp_)) goto LA7;
					i_1 = ((NI) (res_1));
					L_1 += a_p0[i_1].len;
					res_1 += ((NI)1);
				} LA7: ;
			}
		}
		result = rawNewString((L_1));
		prepareAdd((&result), a_p0[((NI)0)].len + 0);
appendString((&result), a_p0[((NI)0)]);
		{
			NI i_2;
			NI colontmp__2;
			NI res_2;
			i_2 = (NI)0;
			colontmp__2 = (NI)0;
			colontmp__2 = (a_p0Len_0-1);
			res_2 = ((NI)1);
			{
				while (1) {
					if (!(res_2 <= colontmp__2)) goto LA10;
					i_2 = ((NI) (res_2));
					prepareAdd((&result), sep_p1.len + 0);
appendString((&result), sep_p1);
					prepareAdd((&result), a_p0[i_2].len + 0);
appendString((&result), a_p0[i_2]);
					res_2 += ((NI)1);
				} LA10: ;
			}
		}
	}
	goto LA1_;
LA3_: ;
	{
		result = TM__JGc9b9bh2D3nTdUR7TGyq8aA_7;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHexImpl__pureZstrutils_u777)(NU64 x_p0, NI len_p1, NIM_BOOL handleNegative_p2) {
	NimStringV2 result;
	NU64 n_1;
	n_1 = x_p0;
	result = mnewString(len_p1);
	{
		NI j_1;
		NI colontmp_;
		NI res_1;
		j_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(len_p1 - ((NI)1));
		res_1 = colontmp_;
		{
			while (1) {
				if (!(((NI)0) <= res_1)) goto LA3;
				j_1 = ((NI) (res_1));
				nimPrepareStrMutationV2((&result));
				result.p->data[j_1] = TM__JGc9b9bh2D3nTdUR7TGyq8aA_9.p->data[((NI) ((NU64)(n_1 & 15ULL)))];
				n_1 = (NU64)((NU64)(n_1) >> (NU64)(((NI)4) & (64 - 1)));
				{
					NIM_BOOL T6_;
					T6_ = (NIM_BOOL)0;
					T6_ = (n_1 == 0ULL);
					if (!(T6_)) goto LA7_;
					T6_ = handleNegative_p2;
LA7_: ;
					if (!T6_) goto LA8_;
					n_1 = 18446744073709551615ULL;
				}
LA8_: ;
				res_1 -= ((NI)1);
			} LA3: ;
		}
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHex__pureZstrutils_u2113)(NI x_p0, NI len_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = toHexImpl__pureZstrutils_u777(((NU64) (((NI64) (x_p0)))), len_p1, (x_p0 < ((NI)0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstrutils_u2385)(NimStringV2* dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			if (!(colontmp_ < ((NI)7))) goto LA2;
			if (dest_p0[(colontmp_)- 0].p && !(dest_p0[(colontmp_)- 0].p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0[(colontmp_)- 0].p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
}
