/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@psystem@sexceptions.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@psystem@sexceptions.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA;
typedef struct tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA;
typedef struct tyObject_Defect__EL9aN6agFLgcb8D9bbKrC9cFA tyObject_Defect__EL9aN6agFLgcb8D9bbKrC9cFA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg tySequence__TM0VfWZgOhRIJ9bpQyFJFrg;
typedef struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content;
typedef struct tyObject_GcEnv__ty5V9abvlcU5gUSzebxyPfA tyObject_GcEnv__ty5V9abvlcU5gUSzebxyPfA;
typedef struct tyObject_CellSeq__c1mlWbdu8MKOYHCEfr7HYw tyObject_CellSeq__c1mlWbdu8MKOYHCEfr7HYw;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__qWMgAQ69bujLbXK1q7BIKhw tyObject_CellSeq__qWMgAQ69bujLbXK1q7BIKhw;
typedef struct tyTuple__lajVwTJCO1UJ9cuSGuSoK9bg tyTuple__lajVwTJCO1UJ9cuSGuSoK9bg;
typedef struct tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA;
typedef struct tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw;
typedef struct tyObject_OSError__gig8WTVgAVkHh283RtPVTA tyObject_OSError__gig8WTVgAVkHh283RtPVTA;
typedef struct tyObject_IOError__AXFT9bUzu1dBeVQnOESkmtQ tyObject_IOError__AXFT9bUzu1dBeVQnOESkmtQ;
typedef struct tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw;
typedef struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA {
	NI rc;
	NI rootIdx;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg {
  NI len; tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__TM0VfWZgOhRIJ9bpQyFJFrg trace;
	Exception* up;
};
struct tyObject_Defect__EL9aN6agFLgcb8D9bbKrC9cFA {
	Exception Sup;
};
struct tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA {
	tyObject_Defect__EL9aN6agFLgcb8D9bbKrC9cFA Sup;
};
struct tyObject_CellSeq__c1mlWbdu8MKOYHCEfr7HYw {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__qWMgAQ69bujLbXK1q7BIKhw {
	NI len;
	NI cap;
	tyTuple__lajVwTJCO1UJ9cuSGuSoK9bg* d;
};
struct tyObject_GcEnv__ty5V9abvlcU5gUSzebxyPfA {
	tyObject_CellSeq__c1mlWbdu8MKOYHCEfr7HYw traceStack;
	tyObject_CellSeq__qWMgAQ69bujLbXK1q7BIKhw toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw {
	Exception Sup;
};
struct tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA {
	tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw Sup;
};
struct tyObject_OSError__gig8WTVgAVkHh283RtPVTA {
	tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw Sup;
	NI32 errorCode;
};
struct tyObject_IOError__AXFT9bUzu1dBeVQnOESkmtQ {
	tyObject_CatchableError__9cwovWjCGBSd6pVOQODD7sw Sup;
};
struct tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw {
	tyObject_Defect__EL9aN6agFLgcb8D9bbKrC9cFA Sup;
};
struct tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__TM0VfWZgOhRIJ9bpQyFJFrg_Content { NI cap; tyObject_StackTraceEntry__F9cToGVssm9ab1JX9bbqWCYpg data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u37)(tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3538)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3740)(tySequence__TM0VfWZgOhRIJ9bpQyFJFrg dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u49)(tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3059)(tyObject_CellSeq__c1mlWbdu8MKOYHCEfr7HYw* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3067)(tyObject_CellSeq__c1mlWbdu8MKOYHCEfr7HYw* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparseutils_u330)(tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparseutils_u342)(tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZoserrors_u60)(tyObject_OSError__gig8WTVgAVkHh283RtPVTA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZoserrors_u72)(tyObject_OSError__gig8WTVgAVkHh283RtPVTA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u9110)(tyObject_IOError__AXFT9bUzu1dBeVQnOESkmtQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u9122)(tyObject_IOError__AXFT9bUzu1dBeVQnOESkmtQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4591)(tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4603)(tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw* dest_p0, void* env_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__z1bPK6E04CoQaHIh4Rm5rA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__hxmI0FYjM9anPt7Bv1LM5TA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__gig8WTVgAVkHh283RtPVTA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__AXFT9bUzu1dBeVQnOESkmtQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__VGLiEs425pQTea1LYjRwHw_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4183;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_2[4] = {3701606400, 1285336064, 3209554176, 1456417536};
N_LIB_PRIVATE TNimTypeV2 NTIv2__z1bPK6E04CoQaHIh4Rm5rA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u56, .size = sizeof(tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA), .align = (NI16) NIM_ALIGNOF(tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_2, .traceImpl = (void*)eqtrace___stdZassertions_u49, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[4] = {3701606400, 1285336064, 170875392, 428396544};
N_LIB_PRIVATE TNimTypeV2 NTIv2__hxmI0FYjM9anPt7Bv1LM5TA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u60, .size = sizeof(tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA), .align = (NI16) NIM_ALIGNOF(tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)eqtrace___pureZparseutils_u342, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_4[4] = {3701606400, 1285336064, 170875392, 675043584};
N_LIB_PRIVATE TNimTypeV2 NTIv2__gig8WTVgAVkHh283RtPVTA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u62, .size = sizeof(tyObject_OSError__gig8WTVgAVkHh283RtPVTA), .align = (NI16) NIM_ALIGNOF(tyObject_OSError__gig8WTVgAVkHh283RtPVTA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_4, .traceImpl = (void*)eqtrace___stdZoserrors_u72, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[4] = {3701606400, 1285336064, 170875392, 1901328640};
N_LIB_PRIVATE TNimTypeV2 NTIv2__AXFT9bUzu1dBeVQnOESkmtQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u64, .size = sizeof(tyObject_IOError__AXFT9bUzu1dBeVQnOESkmtQ), .align = (NI16) NIM_ALIGNOF(tyObject_IOError__AXFT9bUzu1dBeVQnOESkmtQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_5, .traceImpl = (void*)eqtrace___system_u9122, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_6[4] = {3701606400, 1285336064, 3209554176, 1658982912};
N_LIB_PRIVATE TNimTypeV2 NTIv2__VGLiEs425pQTea1LYjRwHw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u66, .size = sizeof(tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_6, .traceImpl = (void*)eqtrace___system_u4603, .flags = 0};
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__d5hGPGFUGPhHyZPyxREKqA*) (T5_));
		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		rememberCycle__system_u3538(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u37)(tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3740((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4183);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZassertions_u37(((tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, add__system_u3059)(tyObject_CellSeq__c1mlWbdu8MKOYHCEfr7HYw* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		resize__system_u3067(s_p0);
	}
LA3_: ;
	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	p_1 = ((void**) (q_p0));
	{
		tyObject_GcEnv__ty5V9abvlcU5gUSzebxyPfA* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		j_1 = ((tyObject_GcEnv__ty5V9abvlcU5gUSzebxyPfA*) (env_p1));
		add__system_u3059((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u49)(tyObject_AssertionDefect__z1bPK6E04CoQaHIh4Rm5rA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparseutils_u330)(tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3740((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pureZparseutils_u330(((tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparseutils_u342)(tyObject_ValueError__hxmI0FYjM9anPt7Bv1LM5TA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZoserrors_u60)(tyObject_OSError__gig8WTVgAVkHh283RtPVTA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3740((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZoserrors_u60(((tyObject_OSError__gig8WTVgAVkHh283RtPVTA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZoserrors_u72)(tyObject_OSError__gig8WTVgAVkHh283RtPVTA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u9110)(tyObject_IOError__AXFT9bUzu1dBeVQnOESkmtQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3740((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u9110(((tyObject_IOError__AXFT9bUzu1dBeVQnOESkmtQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u9122)(tyObject_IOError__AXFT9bUzu1dBeVQnOESkmtQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4591)(tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3740((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4591(((tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4603)(tyObject_IndexDefect__VGLiEs425pQTea1LYjRwHw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
