/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pterminal.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@pterminal.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_PTerminalcolonObjectType___W4ZHy3CgMvZO57EFVAYOhQ tyObject_PTerminalcolonObjectType___W4ZHy3CgMvZO57EFVAYOhQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_IOctl_WinSize__pUn1wcYH7mfsFcPOF4j9bGw tyObject_IOctl_WinSize__pUn1wcYH7mfsFcPOF4j9bGw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_IOctl_WinSize__pUn1wcYH7mfsFcPOF4j9bGw {
	unsigned short ws_row;
	unsigned short ws_col;
	unsigned short ws_xpixel;
	unsigned short ws_ypixel;
};
typedef NI tyArray__B1P0aOtR4tSgZP8DDApcoA[3];
typedef NI tyArray__EcyNQlLBiPAaRkJH9aQCXwA[1];
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u254)(FILE* f_p0, NimStringV2 s_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__pureZterminal_u274)(NimStringV2* result_p0, NimStringV2 value_p1);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__pureZterminal_u287)(NimStringV2* result_p0, NI value_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NIMCALL(NI, parseSaturatedNatural__pureZparseutils_u986)(NimStringV2 s_p0, NI* b_p1, NI start_p2);
N_LIB_PRIVATE N_NIMCALL(NI, terminalWidthIoctl__pureZterminal_u122)(NI* fds_p0, NI fds_p0Len_0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(int, open__pureZterminal_u185)(NCSTRING a1_p0, int a2_p1, mode_t mode_p2);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, terminalHeightIoctl__pureZterminal_u167)(NI* fds_p0, NI fds_p0Len_0);
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__CN3raB9atujkEiPpxYAdlgQ_2 = { 4 | NIM_STRLIT_FLAG, "\033[2J" };
static const NimStringV2 TM__CN3raB9atujkEiPpxYAdlgQ_3 = {4, (NimStrPayload*)&TM__CN3raB9atujkEiPpxYAdlgQ_2};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__CN3raB9atujkEiPpxYAdlgQ_4 = { 2 | NIM_STRLIT_FLAG, "\033[" };
static const NimStringV2 TM__CN3raB9atujkEiPpxYAdlgQ_5 = {2, (NimStrPayload*)&TM__CN3raB9atujkEiPpxYAdlgQ_4};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__CN3raB9atujkEiPpxYAdlgQ_6 = { 1 | NIM_STRLIT_FLAG, ";" };
static const NimStringV2 TM__CN3raB9atujkEiPpxYAdlgQ_7 = {1, (NimStrPayload*)&TM__CN3raB9atujkEiPpxYAdlgQ_6};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__CN3raB9atujkEiPpxYAdlgQ_8 = { 1 | NIM_STRLIT_FLAG, "f" };
static const NimStringV2 TM__CN3raB9atujkEiPpxYAdlgQ_9 = {1, (NimStrPayload*)&TM__CN3raB9atujkEiPpxYAdlgQ_8};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__CN3raB9atujkEiPpxYAdlgQ_10 = { 7 | NIM_STRLIT_FLAG, "COLUMNS" };
static const NimStringV2 TM__CN3raB9atujkEiPpxYAdlgQ_11 = {7, (NimStrPayload*)&TM__CN3raB9atujkEiPpxYAdlgQ_10};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__CN3raB9atujkEiPpxYAdlgQ_12 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__CN3raB9atujkEiPpxYAdlgQ_13 = {0, (NimStrPayload*)&TM__CN3raB9atujkEiPpxYAdlgQ_12};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__CN3raB9atujkEiPpxYAdlgQ_15 = { 5 | NIM_STRLIT_FLAG, "LINES" };
static const NimStringV2 TM__CN3raB9atujkEiPpxYAdlgQ_16 = {5, (NimStrPayload*)&TM__CN3raB9atujkEiPpxYAdlgQ_15};
static const NimStringV2 TM__CN3raB9atujkEiPpxYAdlgQ_17 = {0, (NimStrPayload*)&TM__CN3raB9atujkEiPpxYAdlgQ_12};
static NIM_CONST tyArray__B1P0aOtR4tSgZP8DDApcoA TM__CN3raB9atujkEiPpxYAdlgQ_14 = {((NI)0),
((NI)1),
((NI)2)}
;
N_LIB_PRIVATE NIM_THREADVAR tyObject_PTerminalcolonObjectType___W4ZHy3CgMvZO57EFVAYOhQ* gTerm__pureZterminal_u10;
N_LIB_PRIVATE NIM_THREADVAR NI gFG__pureZterminal_u382;
N_LIB_PRIVATE NIM_THREADVAR NI gBG__pureZterminal_u383;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4183;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4183);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eraseScreen__pureZterminal_u380)(FILE* f_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	write__stdZsyncio_u254(f_p0, TM__CN3raB9atujkEiPpxYAdlgQ_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, setCursorPos__pureZterminal_u257)(FILE* f_p0, NI x_p1, NI y_p2) {
	NimStringV2 colontmpD_;
	NimStringV2 T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T2_.len = 0; T2_.p = NIM_NIL;
	{
		NimStringV2 fmtRes_1;
		fmtRes_1.len = 0; fmtRes_1.p = NIM_NIL;
		fmtRes_1 = rawNewString(((NI)55));
		formatValue__pureZterminal_u274((&fmtRes_1), TM__CN3raB9atujkEiPpxYAdlgQ_5);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		formatValue__pureZterminal_u287((&fmtRes_1), (NI)(y_p2 + ((NI)1)));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		prepareAdd((&fmtRes_1), 1);
appendString((&fmtRes_1), TM__CN3raB9atujkEiPpxYAdlgQ_7);
		formatValue__pureZterminal_u287((&fmtRes_1), (NI)(x_p1 + ((NI)1)));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		prepareAdd((&fmtRes_1), 1);
appendString((&fmtRes_1), TM__CN3raB9atujkEiPpxYAdlgQ_9);
		colontmpD_ = fmtRes_1;
		T2_ = colontmpD_;
	}
	write__stdZsyncio_u254(f_p0, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(NI, terminalWidthIoctl__pureZterminal_u122)(NI* fds_p0, NI fds_p0Len_0) {
	NI result;
	tyObject_IOctl_WinSize__pUn1wcYH7mfsFcPOF4j9bGw win_1;
{	nimZeroMem((void*)(&win_1), sizeof(tyObject_IOctl_WinSize__pUn1wcYH7mfsFcPOF4j9bGw));
	{
		NI* fd_1;
		NI i_1;
		fd_1 = (NI*)0;
		i_1 = ((NI)0);
		{
			while (1) {
				if (!(i_1 < fds_p0Len_0)) goto LA3;
				fd_1 = (&fds_p0[i_1]);
				{
					NI T6_;
					T6_ = (NI)0;
					T6_ = ioctl(((int) ((*fd_1))), TIOCGWINSZ, (&win_1));
					if (!!((T6_ == ((NI)-1)))) goto LA7_;
					result = ((NI) (win_1.ws_col));
					goto BeforeRet_;
				}
LA7_: ;
				i_1 += ((NI)1);
			} LA3: ;
		}
	}
	result = ((NI)0);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(int, open__pureZterminal_u185)(NCSTRING a1_p0, int a2_p1, mode_t mode_p2) {
	int result;
	result = open(a1_p0, a2_p1, mode_p2);
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, terminalWidth__pureZterminal_u180)(void) {
	NI result;
	NimStringV2 s_1;
	NimStringV2 cterm_1;
	NI w_1;
	int fd_1;
	NCSTRING T15_;
	int T21_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	s_1.len = 0; s_1.p = NIM_NIL;
	cterm_1.len = 0; cterm_1.p = NIM_NIL;
	w_1 = ((NI)0);
	s_1 = getEnv__stdZenvvars_u15(TM__CN3raB9atujkEiPpxYAdlgQ_11, TM__CN3raB9atujkEiPpxYAdlgQ_13);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NIM_BOOL T4_;
		NIM_BOOL T5_;
		NI T7_;
		T4_ = (NIM_BOOL)0;
		T5_ = (NIM_BOOL)0;
		T5_ = (((NI)0) < s_1.len);
		if (!(T5_)) goto LA6_;
		T7_ = (NI)0;
		T7_ = parseSaturatedNatural__pureZparseutils_u986(s_1, (&w_1), ((NI)0));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T5_ = (((NI)0) < T7_);
LA6_: ;
		T4_ = T5_;
		if (!(T4_)) goto LA8_;
		T4_ = (((NI)0) < w_1);
LA8_: ;
		if (!T4_) goto LA9_;
		result = w_1;
		if (cterm_1.p && !(cterm_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cterm_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
		goto BeforeRet_;
	}
LA9_: ;
	w_1 = terminalWidthIoctl__pureZterminal_u122(TM__CN3raB9atujkEiPpxYAdlgQ_14, 3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		if (!(((NI)0) < w_1)) goto LA13_;
		result = w_1;
		if (cterm_1.p && !(cterm_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cterm_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
		goto BeforeRet_;
	}
LA13_: ;
	cterm_1 = mnewString(((NI) (L_ctermid)));
	T15_ = (NCSTRING)0;
	T15_ = ctermid(nimToCStringConv(cterm_1));
	fd_1 = open__pureZterminal_u185(T15_, ((int)0), ((mode_t)0));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		tyArray__EcyNQlLBiPAaRkJH9aQCXwA T20_;
		if (!!((fd_1 == ((NI32)-1)))) goto LA18_;
		T20_[0] = ((NI) (fd_1));
		w_1 = terminalWidthIoctl__pureZterminal_u122(T20_, 1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA18_: ;
	T21_ = (int)0;
	T21_ = close(fd_1);
	(void)(T21_);
	{
		if (!(((NI)0) < w_1)) goto LA24_;
		result = w_1;
		if (cterm_1.p && !(cterm_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cterm_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
		goto BeforeRet_;
	}
LA24_: ;
	result = ((NI)80);
	if (cterm_1.p && !(cterm_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cterm_1.p);
}
	if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		if (cterm_1.p && !(cterm_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cterm_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, terminalHeightIoctl__pureZterminal_u167)(NI* fds_p0, NI fds_p0Len_0) {
	NI result;
	tyObject_IOctl_WinSize__pUn1wcYH7mfsFcPOF4j9bGw win_1;
{	nimZeroMem((void*)(&win_1), sizeof(tyObject_IOctl_WinSize__pUn1wcYH7mfsFcPOF4j9bGw));
	{
		NI* fd_1;
		NI i_1;
		fd_1 = (NI*)0;
		i_1 = ((NI)0);
		{
			while (1) {
				if (!(i_1 < fds_p0Len_0)) goto LA3;
				fd_1 = (&fds_p0[i_1]);
				{
					NI T6_;
					T6_ = (NI)0;
					T6_ = ioctl(((int) ((*fd_1))), TIOCGWINSZ, (&win_1));
					if (!!((T6_ == ((NI)-1)))) goto LA7_;
					result = ((NI) (win_1.ws_row));
					goto BeforeRet_;
				}
LA7_: ;
				i_1 += ((NI)1);
			} LA3: ;
		}
	}
	result = ((NI)0);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, terminalHeight__pureZterminal_u234)(void) {
	NI result;
	NimStringV2 s_1;
	NimStringV2 cterm_1;
	NI h_1;
	int fd_1;
	NCSTRING T15_;
	int T21_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	s_1.len = 0; s_1.p = NIM_NIL;
	cterm_1.len = 0; cterm_1.p = NIM_NIL;
	h_1 = ((NI)0);
	s_1 = getEnv__stdZenvvars_u15(TM__CN3raB9atujkEiPpxYAdlgQ_16, TM__CN3raB9atujkEiPpxYAdlgQ_17);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NIM_BOOL T4_;
		NIM_BOOL T5_;
		NI T7_;
		T4_ = (NIM_BOOL)0;
		T5_ = (NIM_BOOL)0;
		T5_ = (((NI)0) < s_1.len);
		if (!(T5_)) goto LA6_;
		T7_ = (NI)0;
		T7_ = parseSaturatedNatural__pureZparseutils_u986(s_1, (&h_1), ((NI)0));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T5_ = (((NI)0) < T7_);
LA6_: ;
		T4_ = T5_;
		if (!(T4_)) goto LA8_;
		T4_ = (((NI)0) < h_1);
LA8_: ;
		if (!T4_) goto LA9_;
		result = h_1;
		if (cterm_1.p && !(cterm_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cterm_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
		goto BeforeRet_;
	}
LA9_: ;
	h_1 = terminalHeightIoctl__pureZterminal_u167(TM__CN3raB9atujkEiPpxYAdlgQ_14, 3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		if (!(((NI)0) < h_1)) goto LA13_;
		result = h_1;
		if (cterm_1.p && !(cterm_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cterm_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
		goto BeforeRet_;
	}
LA13_: ;
	cterm_1 = mnewString(((NI) (L_ctermid)));
	T15_ = (NCSTRING)0;
	T15_ = ctermid(nimToCStringConv(cterm_1));
	fd_1 = open__pureZterminal_u185(T15_, ((int)0), ((mode_t)0));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		tyArray__EcyNQlLBiPAaRkJH9aQCXwA T20_;
		if (!!((fd_1 == ((NI32)-1)))) goto LA18_;
		T20_[0] = ((NI) (fd_1));
		h_1 = terminalHeightIoctl__pureZterminal_u167(T20_, 1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA18_: ;
	T21_ = (int)0;
	T21_ = close(fd_1);
	(void)(T21_);
	{
		if (!(((NI)0) < h_1)) goto LA24_;
		result = h_1;
		if (cterm_1.p && !(cterm_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cterm_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
		goto BeforeRet_;
	}
LA24_: ;
	result = ((NI)0);
	if (cterm_1.p && !(cterm_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cterm_1.p);
}
	if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		if (cterm_1.p && !(cterm_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(cterm_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
