/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@ptimes.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@ptimes.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_TimezonecolonObjectType___yKABNBebGt80CWsNFwZz3Q tyObject_TimezonecolonObjectType___yKABNBebGt80CWsNFwZz3Q;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___yKABNBebGt80CWsNFwZz3Q* utcInstance__pureZtimes_u1999;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___yKABNBebGt80CWsNFwZz3Q* localInstance__pureZtimes_u2000;
