/* Generated by Nim Compiler v2.2.8 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread -Os -fno-ident   -I/home/drunkenalcoholic/.local/share/grabnim/nim-2.2.8/lib -I/home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/src -o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@punicode.nim.c.o /home/drunkenalcoholic/Projects/GitHub/Vyrnexis/Nymph/.nimcache/@punicode.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NIMCALL(NI, validateUtf8__pureZunicode_u342)(NIM_CHAR* s_p0, NI s_p0Len_0) {
	NI result;
	NI i_1;
	NI L_1;
{	i_1 = ((NI)0);
	L_1 = s_p0Len_0;
	{
		while (1) {
			if (!(i_1 < L_1)) goto LA2;
			{
				if (!((NU64)(((NU) (((NU8)(s_p0[i_1]))))) <= (NU64)(((NU)127)))) goto LA5_;
				i_1 += ((NI)1);
			}
			goto LA3_;
LA5_: ;
			{
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)5) & (64 - 1))) == ((NU)6))) goto LA8_;
				{
					if (!((NU64)(((NU) (((NU8)(s_p0[i_1]))))) < (NU64)(((NU)194)))) goto LA12_;
					result = i_1;
					goto BeforeRet_;
				}
LA12_: ;
				{
					NIM_BOOL T16_;
					T16_ = (NIM_BOOL)0;
					T16_ = ((NI)(i_1 + ((NI)1)) < L_1);
					if (!(T16_)) goto LA17_;
					T16_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(i_1 + ((NI)1))]))))) >> (NU64)(((NI)6) & (64 - 1))) == ((NU)2));
LA17_: ;
					if (!T16_) goto LA18_;
					i_1 += ((NI)2);
				}
				goto LA14_;
LA18_: ;
				{
					result = i_1;
					goto BeforeRet_;
				}
LA14_: ;
			}
			goto LA3_;
LA8_: ;
			{
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)4) & (64 - 1))) == ((NU)14))) goto LA22_;
				{
					NIM_BOOL T26_;
					NIM_BOOL T27_;
					T26_ = (NIM_BOOL)0;
					T27_ = (NIM_BOOL)0;
					T27_ = ((NI)(i_1 + ((NI)2)) < L_1);
					if (!(T27_)) goto LA28_;
					T27_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(i_1 + ((NI)1))]))))) >> (NU64)(((NI)6) & (64 - 1))) == ((NU)2));
LA28_: ;
					T26_ = T27_;
					if (!(T26_)) goto LA29_;
					T26_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(i_1 + ((NI)2))]))))) >> (NU64)(((NI)6) & (64 - 1))) == ((NU)2));
LA29_: ;
					if (!T26_) goto LA30_;
					i_1 += ((NI)3);
				}
				goto LA24_;
LA30_: ;
				{
					result = i_1;
					goto BeforeRet_;
				}
LA24_: ;
			}
			goto LA3_;
LA22_: ;
			{
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)3) & (64 - 1))) == ((NU)30))) goto LA34_;
				{
					NIM_BOOL T38_;
					NIM_BOOL T39_;
					NIM_BOOL T40_;
					T38_ = (NIM_BOOL)0;
					T39_ = (NIM_BOOL)0;
					T40_ = (NIM_BOOL)0;
					T40_ = ((NI)(i_1 + ((NI)3)) < L_1);
					if (!(T40_)) goto LA41_;
					T40_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(i_1 + ((NI)1))]))))) >> (NU64)(((NI)6) & (64 - 1))) == ((NU)2));
LA41_: ;
					T39_ = T40_;
					if (!(T39_)) goto LA42_;
					T39_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(i_1 + ((NI)2))]))))) >> (NU64)(((NI)6) & (64 - 1))) == ((NU)2));
LA42_: ;
					T38_ = T39_;
					if (!(T38_)) goto LA43_;
					T38_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(i_1 + ((NI)3))]))))) >> (NU64)(((NI)6) & (64 - 1))) == ((NU)2));
LA43_: ;
					if (!T38_) goto LA44_;
					i_1 += ((NI)4);
				}
				goto LA36_;
LA44_: ;
				{
					result = i_1;
					goto BeforeRet_;
				}
LA36_: ;
			}
			goto LA3_;
LA34_: ;
			{
				result = i_1;
				goto BeforeRet_;
			}
LA3_: ;
		} LA2: ;
	}
	result = ((NI)-1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nucruneLen)(NIM_CHAR* s_p0, NI s_p0Len_0) {
	NI result;
	NI i_1;
	result = ((NI)0);
	i_1 = ((NI)0);
	{
		while (1) {
			if (!(i_1 < s_p0Len_0)) goto LA2;
			{
				if (!((NU64)(((NU) (((NU8)(s_p0[i_1]))))) <= (NU64)(((NU)127)))) goto LA5_;
				i_1 += ((NI)1);
			}
			goto LA3_;
LA5_: ;
			{
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)5) & (64 - 1))) == ((NU)6))) goto LA8_;
				i_1 += ((NI)2);
			}
			goto LA3_;
LA8_: ;
			{
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)4) & (64 - 1))) == ((NU)14))) goto LA11_;
				i_1 += ((NI)3);
			}
			goto LA3_;
LA11_: ;
			{
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)3) & (64 - 1))) == ((NU)30))) goto LA14_;
				i_1 += ((NI)4);
			}
			goto LA3_;
LA14_: ;
			{
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)2) & (64 - 1))) == ((NU)62))) goto LA17_;
				i_1 += ((NI)5);
			}
			goto LA3_;
LA17_: ;
			{
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)1) & (64 - 1))) == ((NU)126))) goto LA20_;
				i_1 += ((NI)6);
			}
			goto LA3_;
LA20_: ;
			{
				i_1 += ((NI)1);
			}
LA3_: ;
			result += ((NI)1);
		} LA2: ;
	}
	return result;
}
